
import type { Car } from './types';

export const cars: Car[] = [
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 1999000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Front',
      rear: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Rear',
      left: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Left',
      right: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Interior+Rear',
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 12500,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 670,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4979, width: 1964, height: 1445 },
    },
    features: ['Hệ thống lái tự động Autopilot', 'Màn hình cảm ứng 17"', 'Dẫn động 4 bánh toàn thời gian', 'Nội thất cao cấp'],
    reviews: [
      { name: 'Alex', rating: 5, comment: 'Tốc độ và phạm vi hoạt động đáng kinh ngạc. Tương lai là đây.' },
      { name: 'Beth', rating: 4, comment: 'Yêu công nghệ, nhưng việc sạc pin hơi bất tiện khi đi xa.' },
    ],
  },
  {
    id: 2,
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    price: 2860000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Front',
      rear: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Rear',
      left: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Left',
      right: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Porsche+911+Carrera+Interior+Rear',
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Silver',
    interiorColor: 'Red',
    drivetrain: 'RWD',
    mileage: 5600,
    seatingCapacity: 4,
    status: 'Available',
    specs: {
      engine: '3.0L Twin-Turbo Boxer 6',
      horsepower: 379,
      fuelConsumption: '10.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4519, width: 1852, height: 1298 },
    },
    features: ['Động cơ đặt sau', 'Hệ thống treo chủ động Porsche (PASM)', 'Gói Sport Chrono', 'Nội thất da'],
    reviews: [
      { name: 'Charlie', rating: 5, comment: 'Trải nghiệm lái không thể so sánh. Một chiếc xe thực thụ cho người lái.' },
      { name: 'Diana', rating: 5, comment: 'Thiết kế biểu tượng và hiệu suất phấn khích.' },
    ],
  },
  {
    id: 3,
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    price: 1060000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Front',
      rear: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Rear',
      left: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Left',
      right: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Ford+Mustang+GT+Interior+Rear',
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Blue',
    interiorColor: 'Black',
    drivetrain: 'RWD',
    mileage: 21000,
    seatingCapacity: 4,
    status: 'Sold',
    specs: {
      engine: '5.0L V8',
      horsepower: 480,
      fuelConsumption: '13.1L/100km',
      safetyRating: 4,
      dimensions: { length: 4788, width: 1915, height: 1379 },
    },
    features: ['Hộp số tự động 10 cấp', 'Bảng đồng hồ kỹ thuật số', 'Hệ thống giảm xóc MagneRide', 'Hệ thống ống xả van chủ động'],
    reviews: [
      { name: 'Ethan', rating: 4, comment: 'Tiếng gầm V8 gây nghiện. Giá trị tuyệt vời cho sức mạnh.' },
      { name: 'Fiona', rating: 4, comment: 'Lái vui, nhưng nội thất có thể tinh tế hơn.' },
    ],
  },
  {
    id: 4,
    brand: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    price: 780000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Front',
      rear: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Rear',
      left: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Left',
      right: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Interior+Rear',
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 35000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 219,
      fuelConsumption: '5.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4600, width: 1855, height: 1685 },
    },
    features: ['Dẫn động 4 bánh toàn thời gian', 'Gói an toàn Toyota Safety Sense 2.5', 'Kết nối Apple CarPlay', 'Cảnh báo điểm mù'],
    reviews: [
      { name: 'George', rating: 5, comment: 'Tiết kiệm nhiên liệu đáng kinh ngạc và rất thiết thực cho gia đình tôi.' },
      { name: 'Hannah', rating: 4, comment: 'SUV vững chắc, đáng tin cậy. Chỉ mong nó nhanh hơn một chút.' },
    ],
  },
  {
    id: 5,
    brand: 'BMW',
    model: 'M3',
    year: 2024,
    price: 1900000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=BMW+M3+Front',
      rear: 'https://placehold.co/600x400.png?text=BMW+M3+Rear',
      left: 'https://placehold.co/600x400.png?text=BMW+M3+Left',
      right: 'https://placehold.co/600x400.png?text=BMW+M3+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=BMW+M3+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=BMW+M3+Interior+Rear',
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Sedan',
    exteriorColor: 'Green',
    interiorColor: 'Tan',
    drivetrain: 'RWD',
    mileage: 8900,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L M TwinPower Turbo inline 6-cylinder',
      horsepower: 473,
      fuelConsumption: '12.3L/100km',
      safetyRating: 5,
      dimensions: { length: 4794, width: 1903, height: 1437 },
    },
    features: ['Vi sai M Sport', 'Hệ thống treo thích ứng M', 'Mui xe bằng sợi carbon', 'Ghế thể thao M'],
    reviews: [
      { name: 'Ian', rating: 5, comment: 'Sự pha trộn hoàn hảo giữa xe thể thao và xe đi hàng ngày.' },
      { name: 'Jane', rating: 5, comment: 'Khả năng xử lý sắc như dao cạo. Một niềm vui khi lái trên mọi con đường.' },
    ],
  },
  {
    id: 6,
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 1120000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Front',
      rear: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Rear',
      left: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Left',
      right: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Interior+Rear',
    },
    logo: '/logos/honda.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Compact',
    exteriorColor: 'Red',
    interiorColor: 'Red',
    drivetrain: 'FWD',
    mileage: 15200,
    seatingCapacity: 4,
    status: 'Sold',
    specs: {
      engine: '2.0L Turbocharged VTEC',
      horsepower: 315,
      fuelConsumption: '9.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4594, width: 1890, height: 1407 },
    },
    features: ['Hộp số sàn 6 cấp', 'Hệ thống LogR Datalogger', 'Phanh hiệu suất cao Brembo', 'Cánh gió thể thao'],
    reviews: [
      { name: 'Kevin', rating: 5, comment: 'Chiếc xe dẫn động cầu trước tốt nhất trên thị trường. Chấm hết.' },
      { name: 'Laura', rating: 4, comment: 'Cực kỳ thú vị, nhưng kiểu dáng hơi quá hầm hố đối với tôi.' },
    ],
  },
    {
    id: 7,
    brand: 'Audi',
    model: 'R8',
    year: 2023,
    price: 3965000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Audi+R8+Front',
      rear: 'https://placehold.co/600x400.png?text=Audi+R8+Rear',
      left: 'https://placehold.co/600x400.png?text=Audi+R8+Left',
      right: 'https://placehold.co/600x400.png?text=Audi+R8+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Audi+R8+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Audi+R8+Interior+Rear',
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 9500,
    seatingCapacity: 2,
    status: 'Available',
    specs: {
      engine: '5.2L V10',
      horsepower: 562,
      fuelConsumption: '13.8L/100km',
      safetyRating: 4,
      dimensions: { length: 4429, width: 1940, height: 1236 },
    },
    features: ['Dẫn động 4 bánh Quattro', 'Buồng lái ảo Virtual Cockpit', 'Hệ thống âm thanh Bang & Olufsen', 'Ốp nội thất sợi carbon'],
    reviews: [
      { name: 'Mike', rating: 5, comment: 'Âm thanh V10 say đắm. Một siêu xe bạn có thể lái hàng ngày.' },
      { name: 'Nina', rating: 5, comment: 'Vẻ ngoài tuyệt đẹp và hiệu suất kinh ngạc. Thu hút mọi ánh nhìn.' },
    ],
  },
  {
    id: 8,
    brand: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2024,
    price: 1135000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Front',
      rear: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Rear',
      left: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Left',
      right: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Interior+Rear',
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Brown',
    drivetrain: '4WD',
    mileage: 45000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: '3.0L V6 Turbodiesel',
      horsepower: 285,
      fuelConsumption: '9.4L/100km',
      safetyRating: 3,
      dimensions: { length: 4882, width: 1894, height: 1838 },
    },
    features: ['Hệ thống 4x4 Rock-Trac', 'Khóa vi sai điện tử', 'Thanh cân bằng điện tử', 'Cửa và mui có thể tháo rời'],
    reviews: [
      { name: 'Oscar', rating: 5, comment: 'Không thể ngăn cản khi off-road. Nó có thể đi bất cứ đâu.' },
      { name: 'Penny', rating: 3, comment: 'Tuyệt vời trên đường mòn, nhưng rất xóc và ồn trên đường cao tốc.' },
    ],
  },
  {
    id: 9,
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 1150000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Front',
      rear: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Rear',
      left: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Left',
      right: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Interior+Rear',
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Blue',
    interiorColor: 'White',
    drivetrain: 'RWD',
    mileage: 22000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 283,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4694, width: 1849, height: 1443 },
    },
    features: ['Màn hình cảm ứng 15"', 'Cửa sổ trời toàn cảnh', 'Sạc không dây', 'Ghế da Vegan'],
    reviews: [
      { name: 'Quang', rating: 5, comment: 'Chiếc xe điện tuyệt vời cho việc đi lại hàng ngày. Rất nhanh và hiệu quả.' },
    ],
  },
  {
    id: 10,
    brand: 'Tesla',
    model: 'Model X',
    year: 2022,
    price: 2450000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Front',
      rear: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Rear',
      left: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Left',
      right: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Interior+Rear',
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'White',
    drivetrain: 'AWD',
    mileage: 18000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 670,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 5037, width: 1999, height: 1684 },
    },
    features: ['Cửa cánh chim Falcon Wing', 'Hệ thống lái tự động Autopilot', 'Màn hình cảm ứng 17"', 'Kính chắn gió panorama'],
    reviews: [
      { name: 'Mai', rating: 5, comment: 'Cửa Falcon Wing thật ấn tượng. Rất nhiều không gian cho gia đình.' },
    ],
  },
  {
    id: 11,
    brand: 'Tesla',
    model: 'Model Y',
    year: 2023,
    price: 1380000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Front',
      rear: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Rear',
      left: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Left',
      right: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Interior+Rear',
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 14000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: 'Electric',
      horsepower: 384,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4751, width: 1921, height: 1624 },
    },
    features: ['Không gian chứa đồ lớn', 'Hiệu suất cao', 'Cửa sổ trời toàn cảnh', 'Bơm nhiệt hiệu quả'],
    reviews: [
      { name: 'Anh', rating: 5, comment: 'Sự kết hợp hoàn hảo giữa hiệu suất của Model 3 và tính thực dụng của một chiếc SUV.' },
    ],
  },
  {
    id: 12,
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2022,
    price: 2950000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Front',
      rear: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Rear',
      left: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Left',
      right: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Interior+Rear',
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 28000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L V6 Turbo + Electric Motor',
      horsepower: 455,
      fuelConsumption: '3.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4930, width: 1983, height: 1678 },
    },
    features: ['Hệ thống treo khí nén', 'Porsche Communication Management (PCM)', 'Nội thất da cao cấp', 'Chế độ lái E-Power'],
    reviews: [
      { name: 'Bảo', rating: 5, comment: 'Một chiếc SUV với DNA của xe thể thao. Cảm giác lái tuyệt vời và sang trọng.' },
    ],
  },
  {
    id: 13,
    brand: 'Porsche',
    model: 'Panamera 4',
    year: 2021,
    price: 2680000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Front',
      rear: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Rear',
      left: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Left',
      right: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Interior+Rear',
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 32000,
    seatingCapacity: 4,
    status: 'Available',
    specs: {
      engine: '2.9L Twin-Turbo V6',
      horsepower: 325,
      fuelConsumption: '10.5L/100km',
      safetyRating: 5,
      dimensions: { length: 5049, width: 1937, height: 1423 },
    },
    features: ['Nội thất sang trọng', 'Khả năng vận hành thể thao', 'Cánh gió sau thích ứng', 'Hệ thống âm thanh Bose'],
    reviews: [
      { name: 'Châu', rating: 5, comment: 'Chiếc sedan sang trọng tốt nhất tôi từng lái. Vừa thoải mái vừa thể thao.' },
    ],
  },
  {
    id: 14,
    brand: 'Porsche',
    model: 'Macan',
    year: 2023,
    price: 1980000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Porsche+Macan+Front',
      rear: 'https://placehold.co/600x400.png?text=Porsche+Macan+Rear',
      left: 'https://placehold.co/600x400.png?text=Porsche+Macan+Left',
      right: 'https://placehold.co/600x400.png?text=Porsche+Macan+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Porsche+Macan+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Porsche+Macan+Interior+Rear',
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Blue',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 11000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L Turbo I4',
      horsepower: 261,
      fuelConsumption: '9.2L/100km',
      safetyRating: 5,
      dimensions: { length: 4726, width: 1922, height: 1621 },
    },
    features: ['Hộp số PDK 7 cấp', 'Hệ thống dẫn động 4 bánh toàn thời gian', 'Thiết kế nhỏ gọn, linh hoạt', 'Màn hình cảm ứng 10.9"'],
    reviews: [
      { name: 'Dũng', rating: 4, comment: 'Một chiếc SUV nhỏ gọn tuyệt vời, cảm giác lái rất giống xe Porsche. Hàng ghế sau hơi chật.' },
    ],
  },
  {
    id: 15,
    brand: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 1850000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Ford+Explorer+Front',
      rear: 'https://placehold.co/600x400.png?text=Ford+Explorer+Rear',
      left: 'https://placehold.co/600x400.png?text=Ford+Explorer+Left',
      right: 'https://placehold.co/600x400.png?text=Ford+Explorer+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Ford+Explorer+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Ford+Explorer+Interior+Rear',
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 45000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: '2.3L EcoBoost I4',
      horsepower: 300,
      fuelConsumption: '10.2L/100km',
      safetyRating: 5,
      dimensions: { length: 5049, width: 2004, height: 1778 },
    },
    features: ['7 chỗ ngồi rộng rãi', 'Hệ thống thông tin giải trí SYNC 3', 'Gói an toàn Co-Pilot360', 'Cửa sổ trời panorama'],
    reviews: [
      { name: 'Giang', rating: 4, comment: 'SUV gia đình tuyệt vời, nhiều không gian và công nghệ.' },
    ],
  },
  {
    id: 16,
    brand: 'Ford',
    model: 'Bronco',
    year: 2023,
    price: 1550000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Ford+Bronco+Front',
      rear: 'https://placehold.co/600x400.png?text=Ford+Bronco+Rear',
      left: 'https://placehold.co/600x400.png?text=Ford+Bronco+Left',
      right: 'https://placehold.co/600x400.png?text=Ford+Bronco+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Ford+Bronco+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Ford+Bronco+Interior+Rear',
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Silver',
    interiorColor: 'Gray',
    drivetrain: '4WD',
    mileage: 15000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.7L EcoBoost V6',
      horsepower: 330,
      fuelConsumption: '11.8L/100km',
      safetyRating: 4,
      dimensions: { length: 4811, width: 1928, height: 1852 },
    },
    features: ['Khả năng off-road vượt trội', 'Cửa và mui có thể tháo rời', 'Hệ thống G.O.A.T. Modes', 'Nội thất chống nước'],
    reviews: [
      { name: 'Huy', rating: 5, comment: 'Vua off-road đã trở lại! Vui nhộn và cực kỳ có năng lực.' },
    ],
  },
  {
    id: 17,
    brand: 'Ford',
    model: 'Focus',
    year: 2018,
    price: 480000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Ford+Focus+Front',
      rear: 'https://placehold.co/600x400.png?text=Ford+Focus+Rear',
      left: 'https://placehold.co/600x400.png?text=Ford+Focus+Left',
      right: 'https://placehold.co/600x400.png?text=Ford+Focus+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Ford+Focus+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Ford+Focus+Interior+Rear',
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 65000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: '1.5L EcoBoost',
      horsepower: 180,
      fuelConsumption: '7.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4378, width: 1825, height: 1454 },
    },
    features: ['Cảm giác lái thú vị', 'Tiết kiệm nhiên liệu', 'Hệ thống thông tin giải trí SYNC', 'Thiết kế nhỏ gọn'],
    reviews: [
      { name: 'Khánh', rating: 4, comment: 'Một chiếc xe nhỏ tuyệt vời để đi trong thành phố, cảm giác lái chắc chắn.' },
    ],
  },
  {
    id: 18,
    brand: 'Toyota',
    model: 'Camry Hybrid',
    year: 2022,
    price: 950000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Toyota+Camry+Front',
      rear: 'https://placehold.co/600x400.png?text=Toyota+Camry+Rear',
      left: 'https://placehold.co/600x400.png?text=Toyota+Camry+Left',
      right: 'https://placehold.co/600x400.png?text=Toyota+Camry+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Toyota+Camry+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Toyota+Camry+Interior+Rear',
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Black',
    interiorColor: 'Beige',
    drivetrain: 'FWD',
    mileage: 38000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 208,
      fuelConsumption: '5.1L/100km',
      safetyRating: 5,
      dimensions: { length: 4885, width: 1840, height: 1445 },
    },
    features: ['Độ tin cậy cao', 'Tiết kiệm nhiên liệu xuất sắc', 'Nội thất rộng rãi', 'Gói an toàn Toyota Safety Sense'],
    reviews: [
      { name: 'Linh', rating: 5, comment: 'Chiếc xe hoàn hảo. Đáng tin cậy, thoải mái và tiết kiệm nhiên liệu.' },
    ],
  },
  {
    id: 19,
    brand: 'Toyota',
    model: 'Corolla',
    year: 2021,
    price: 620000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Front',
      rear: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Rear',
      left: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Left',
      right: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Interior+Rear',
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'Blue',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 55000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.8L 4-Cylinder',
      horsepower: 139,
      fuelConsumption: '7.3L/100km',
      safetyRating: 5,
      dimensions: { length: 4630, width: 1780, height: 1435 },
    },
    features: ['Độ bền bỉ', 'Giữ giá', 'Chi phí vận hành thấp', 'Trang bị an toàn tiêu chuẩn'],
    reviews: [
      { name: 'Nam', rating: 4, comment: 'Không có gì thú vị, nhưng nó hoàn thành công việc một cách hoàn hảo và sẽ không làm bạn thất vọng.' },
    ],
  },
  {
    id: 20,
    brand: 'Toyota',
    model: 'Highlander',
    year: 2023,
    price: 1750000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Front',
      rear: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Rear',
      left: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Left',
      right: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Interior+Rear',
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 25000,
    seatingCapacity: 8,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 243,
      fuelConsumption: '6.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4950, width: 1930, height: 1730 },
    },
    features: ['3 hàng ghế', 'Nội thất chất lượng cao', 'Hệ thống giải trí cho hàng ghế sau', 'Cửa sổ trời'],
    reviews: [
      { name: 'Oanh', rating: 5, comment: 'SUV 3 hàng ghế tuyệt vời. Rất nhiều không gian và cực kỳ tiết kiệm nhiên liệu.' },
    ],
  },
  {
    id: 21,
    brand: 'BMW',
    model: 'X5',
    year: 2022,
    price: 2400000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=BMW+X5+Front',
      rear: 'https://placehold.co/600x400.png?text=BMW+X5+Rear',
      left: 'https://placehold.co/600x400.png?text=BMW+X5+Left',
      right: 'https://placehold.co/600x400.png?text=BMW+X5+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=BMW+X5+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=BMW+X5+Interior+Rear',
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'Tan',
    drivetrain: 'AWD',
    mileage: 48000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L Inline 6-cylinder Turbodiesel',
      horsepower: 282,
      fuelConsumption: '7.0L/100km',
      safetyRating: 5,
      dimensions: { length: 4922, width: 2004, height: 1745 },
    },
    features: ['Hệ thống iDrive 7.0', 'Cửa sổ trời panorama Sky Lounge', 'Hệ thống treo khí nén thích ứng', 'Hệ thống hỗ trợ đỗ xe'],
    reviews: [
      { name: 'Phú', rating: 5, comment: 'Sang trọng, mạnh mẽ và cảm giác lái tuyệt vời. Một chiếc SUV hoàn hảo.' },
    ],
  },
  {
    id: 22,
    brand: 'BMW',
    model: '330i',
    year: 2023,
    price: 1450000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=BMW+330i+Front',
      rear: 'https://placehold.co/600x400.png?text=BMW+330i+Rear',
      left: 'https://placehold.co/600x400.png?text=BMW+330i+Left',
      right: 'https://placehold.co/600x400.png?text=BMW+330i+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=BMW+330i+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=BMW+330i+Interior+Rear',
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Red',
    drivetrain: 'RWD',
    mileage: 21000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L TwinPower Turbo I4',
      horsepower: 255,
      fuelConsumption: '7.1L/100km',
      safetyRating: 5,
      dimensions: { length: 4713, width: 1827, height: 1440 },
    },
    features: ['Khung gầm thể thao', 'Phân bổ trọng lượng 50/50', 'Hệ thống Live Cockpit Professional', 'Đèn viền nội thất'],
    reviews: [
      { name: 'Quỳnh', rating: 5, comment: 'Chuẩn mực của dòng sedan thể thao. Cảm giác lái vô cùng phấn khích.' },
    ],
  },
  {
    id: 23,
    brand: 'BMW',
    model: 'Z4',
    year: 2021,
    price: 1750000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=BMW+Z4+Front',
      rear: 'https://placehold.co/600x400.png?text=BMW+Z4+Rear',
      left: 'https://placehold.co/600x400.png?text=BMW+Z4+Left',
      right: 'https://placehold.co/600x400.png?text=BMW+Z4+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=BMW+Z4+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=BMW+Z4+Interior+Rear',
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'RWD',
    mileage: 19000,
    seatingCapacity: 2,
    status: 'Sold',
    specs: {
      engine: '3.0L M TwinPower Turbo inline 6-cylinder',
      horsepower: 382,
      fuelConsumption: '9.0L/100km',
      safetyRating: 4,
      dimensions: { length: 4324, width: 1864, height: 1304 },
    },
    features: ['Mui mềm có thể đóng/mở nhanh', 'Thiết kế roadster cổ điển', 'Hiệu suất mạnh mẽ', 'Ghế thể thao'],
    reviews: [
      { name: 'Sơn', rating: 5, comment: 'Một chiếc roadster tuyệt vời để tận hưởng những ngày đẹp trời. Rất vui khi lái.' },
    ],
  },
  {
    id: 24,
    brand: 'Honda',
    model: 'CR-V Hybrid',
    year: 2023,
    price: 980000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Honda+CRV+Front',
      rear: 'https://placehold.co/600x400.png?text=Honda+CRV+Rear',
      left: 'https://placehold.co/600x400.png?text=Honda+CRV+Left',
      right: 'https://placehold.co/600x400.png?text=Honda+CRV+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Honda+CRV+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Honda+CRV+Interior+Rear',
    },
    logo: '/logos/honda.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 26000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L 4-Cylinder Hybrid',
      horsepower: 204,
      fuelConsumption: '6.4L/100km',
      safetyRating: 5,
      dimensions: { length: 4694, width: 1866, height: 1681 },
    },
    features: ['Gói an toàn Honda Sensing', 'Nội thất rộng rãi', 'Tiết kiệm nhiên liệu', 'Hệ thống âm thanh Bose'],
    reviews: [
      { name: 'Tâm', rating: 5, comment: 'Một chiếc SUV rất thực dụng và đáng tin cậy. Hệ thống hybrid hoạt động mượt mà.' },
    ],
  },
  {
    id: 25,
    brand: 'Honda',
    model: 'Accord',
    year: 2022,
    price: 890000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Honda+Accord+Front',
      rear: 'https://placehold.co/600x400.png?text=Honda+Accord+Rear',
      left: 'https://placehold.co/600x400.png?text=Honda+Accord+Left',
      right: 'https://placehold.co/600x400.png?text=Honda+Accord+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Honda+Accord+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Honda+Accord+Interior+Rear',
    },
    logo: '/logos/honda.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 41000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L 4-Cylinder Hybrid',
      horsepower: 204,
      fuelConsumption: '5.0L/100km',
      safetyRating: 5,
      dimensions: { length: 4971, width: 1862, height: 1450 },
    },
    features: ['Cảm giác lái thú vị', 'Thiết kế fastback', 'Nội thất cao cấp', 'Màn hình cảm ứng 12.3"'],
    reviews: [
      { name: 'Thành', rating: 4, comment: 'Một trong những chiếc sedan cỡ trung tốt nhất. Rộng rãi, hiệu quả và lái hay.' },
    ],
  },
  {
    id: 26,
    brand: 'Honda',
    model: 'HR-V',
    year: 2023,
    price: 720000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Honda+HRV+Front',
      rear: 'https://placehold.co/600x400.png?text=Honda+HRV+Rear',
      left: 'https://placehold.co/600x400.png?text=Honda+HRV+Left',
      right: 'https://placehold.co/600x400.png?text=Honda+HRV+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Honda+HRV+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Honda+HRV+Interior+Rear',
    },
    logo: '/logos/honda.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 19000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.5L Turbo I4',
      horsepower: 177,
      fuelConsumption: '6.7L/100km',
      safetyRating: 5,
      dimensions: { length: 4385, width: 1790, height: 1590 },
    },
    features: ['Thiết kế thể thao', 'Ghế Magic Seat linh hoạt', 'Gói an toàn Honda Sensing', 'Cửa sổ trời'],
    reviews: [
      { name: 'Trang', rating: 4, comment: 'SUV nhỏ gọn tuyệt vời cho thành phố. Rất linh hoạt.' },
    ],
  },
  {
    id: 27,
    brand: 'Audi',
    model: 'Q7',
    year: 2021,
    price: 2150000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Audi+Q7+Front',
      rear: 'https://placehold.co/600x400.png?text=Audi+Q7+Rear',
      left: 'https://placehold.co/600x400.png?text=Audi+Q7+Left',
      right: 'https://placehold.co/600x400.png?text=Audi+Q7+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Audi+Q7+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Audi+Q7+Interior+Rear',
    },
    logo: '/logos/audi.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Blue',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 60000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: '3.0L V6 TDI',
      horsepower: 286,
      fuelConsumption: '8.0L/100km',
      safetyRating: 5,
      dimensions: { length: 5063, width: 1970, height: 1741 },
    },
    features: ['Nội thất công nghệ cao', 'Buồng lái ảo Virtual Cockpit', 'Hệ thống treo khí nén', '3 hàng ghế'],
    reviews: [
      { name: 'Việt', rating: 5, comment: 'Chiếc SUV gia đình sang trọng và thoải mái. Công nghệ rất ấn tượng.' },
    ],
  },
  {
    id: 28,
    brand: 'Audi',
    model: 'A6',
    year: 2022,
    price: 1950000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Audi+A6+Front',
      rear: 'https://placehold.co/600x400.png?text=Audi+A6+Rear',
      left: 'https://placehold.co/600x400.png?text=Audi+A6+Left',
      right: 'https://placehold.co/600x400.png?text=Audi+A6+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Audi+A6+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Audi+A6+Interior+Rear',
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Silver',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 33000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L TFSI I4',
      horsepower: 248,
      fuelConsumption: '7.6L/100km',
      safetyRating: 5,
      dimensions: { length: 4939, width: 1886, height: 1457 },
    },
    features: ['Hệ thống MMI hai màn hình cảm ứng', 'Đèn Matrix LED', 'Nội thất ốp gỗ', 'Hệ thống âm thanh cao cấp'],
    reviews: [
      { name: 'Xuân', rating: 5, comment: 'Một chiếc sedan hạng sang tinh tế. Vận hành êm ái và nội thất tuyệt đẹp.' },
    ],
  },
  {
    id: 29,
    brand: 'Audi',
    model: 'A3',
    year: 2020,
    price: 1100000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Audi+A3+Front',
      rear: 'https://placehold.co/600x400.png?text=Audi+A3+Rear',
      left: 'https://placehold.co/600x400.png?text=Audi+A3+Left',
      right: 'https://placehold.co/600x400.png?text=Audi+A3+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Audi+A3+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Audi+A3+Interior+Rear',
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 42000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.4L TFSI I4',
      horsepower: 150,
      fuelConsumption: '6.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4458, width: 1796, height: 1416 },
    },
    features: ['Buồng lái ảo Virtual Cockpit', 'Thiết kế nhỏ gọn, sang trọng', 'Cửa sổ trời', 'Đèn viền nội thất'],
    reviews: [
      { name: 'Yến', rating: 4, comment: 'Chiếc xe sang cỡ nhỏ tuyệt vời. Hoàn hảo cho việc đi lại trong thành phố.' },
    ],
  },
  {
    id: 30,
    brand: 'Jeep',
    model: 'Grand Cherokee',
    year: 2022,
    price: 2100000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Front',
      rear: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Rear',
      left: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Left',
      right: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Interior+Rear',
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Silver',
    interiorColor: 'Black',
    drivetrain: '4WD',
    mileage: 31000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.6L V6',
      horsepower: 293,
      fuelConsumption: '10.7L/100km',
      safetyRating: 5,
      dimensions: { length: 4914, width: 1968, height: 1799 },
    },
    features: ['Hệ thống 4x4 Quadra-Trac', 'Hệ thống treo khí nén Quadra-Lift', 'Nội thất cao cấp', 'Hệ thống Uconnect 5'],
    reviews: [
      { name: 'An', rating: 5, comment: 'Vừa sang trọng vừa có khả năng off-road. Sự kết hợp tốt nhất của cả hai thế giới.' },
    ],
  },
  {
    id: 31,
    brand: 'Jeep',
    model: 'Compass',
    year: 2021,
    price: 950000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Jeep+Compass+Front',
      rear: 'https://placehold.co/600x400.png?text=Jeep+Compass+Rear',
      left: 'https://placehold.co/600x400.png?text=Jeep+Compass+Left',
      right: 'https://placehold.co/600x400.png?text=Jeep+Compass+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Jeep+Compass+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Jeep+Compass+Interior+Rear',
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Green',
    interiorColor: 'Black',
    drivetrain: '4WD',
    mileage: 40000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.4L I4',
      horsepower: 177,
      fuelConsumption: '9.4L/100km',
      safetyRating: 4,
      dimensions: { length: 4404, width: 1819, height: 1645 },
    },
    features: ['Hệ thống Selec-Terrain', 'Thiết kế đặc trưng của Jeep', 'Cửa sổ trời panorama', 'Màn hình cảm ứng 10.1"'],
    reviews: [
      { name: 'Bình', rating: 4, comment: 'Một chiếc SUV nhỏ gọn có năng lực, cảm giác chắc chắn và an toàn.' },
    ],
  },
  {
    id: 32,
    brand: 'Jeep',
    model: 'Renegade',
    year: 2020,
    price: 780000000,
    images: {
      front: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Front',
      rear: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Rear',
      left: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Left',
      right: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Right',
      interiorFront: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Interior+Front',
      interiorRear: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Interior+Rear',
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Gray',
    drivetrain: '4WD',
    mileage: 45000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.3L Turbo I4',
      horsepower: 177,
      fuelConsumption: '8.7L/100km',
      safetyRating: 4,
      dimensions: { length: 4232, width: 1805, height: 1689 },
    },
    features: ['Thiết kế cá tính', 'Cửa sổ trời My Sky', 'Khả năng off-road tốt trong phân khúc', 'Nhiều chi tiết thú vị'],
    reviews: [
      { name: 'Cường', rating: 4, comment: 'SUV nhỏ nhắn nhưng đầy cá tính. Lái trong thành phố rất vui.' },
    ],
  },
];
