
import type { Car } from './types';

export const cars: Car[] = [
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 1999000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+S+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+S+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Front',
        rear: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Rear',
        side: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Side',
        topDown: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Top',
        wheel: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Console',
        seats: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Tesla+Model+S+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Tesla+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Tesla+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Tesla+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Tesla+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Tesla+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Tesla+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Tesla+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Tesla+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Tesla+Night',
      },
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 12500,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 670,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4979, width: 1964, height: 1445 },
    },
    features: ['Hệ thống lái tự động Autopilot', 'Màn hình cảm ứng 17"', 'Dẫn động 4 bánh toàn thời gian', 'Nội thất cao cấp'],
    reviews: [
      { name: 'Alex', rating: 5, comment: 'Tốc độ và phạm vi hoạt động đáng kinh ngạc. Tương lai là đây.' },
      { name: 'Beth', rating: 4, comment: 'Yêu công nghệ, nhưng việc sạc pin hơi bất tiện khi đi xa.' },
    ],
  },
  {
    id: 2,
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    price: 2860000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+911+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+911+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Porsche+911+Front',
        rear: 'https://placehold.co/600x400.png?text=Porsche+911+Rear',
        side: 'https://placehold.co/600x400.png?text=Porsche+911+Side',
        topDown: 'https://placehold.co/600x400.png?text=Porsche+911+Top',
        wheel: 'https://placehold.co/600x400.png?text=Porsche+911+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Porsche+911+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Porsche+911+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Porsche+911+Console',
        seats: 'https://placehold.co/600x400.png?text=Porsche+911+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Porsche+911+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Porsche+911+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Porsche+911+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Porsche+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Porsche+911+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Porsche+911+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Porsche+911+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Porsche+911+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Porsche+911+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Porsche+911+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Porsche+911+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Porsche+911+Night',
      },
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Silver',
    interiorColor: 'Red',
    drivetrain: 'RWD',
    mileage: 5600,
    seatingCapacity: 4,
    status: 'Available',
    specs: {
      engine: '3.0L Twin-Turbo Boxer 6',
      horsepower: 379,
      fuelConsumption: '10.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4519, width: 1852, height: 1298 },
    },
    features: ['Động cơ đặt sau', 'Hệ thống treo chủ động Porsche (PASM)', 'Gói Sport Chrono', 'Nội thất da'],
    reviews: [
      { name: 'Charlie', rating: 5, comment: 'Trải nghiệm lái không thể so sánh. Một chiếc xe thực thụ cho người lái.' },
      { name: 'Diana', rating: 5, comment: 'Thiết kế biểu tượng và hiệu suất phấn khích.' },
    ],
  },
  {
    id: 3,
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    price: 1060000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Mustang+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Mustang+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Ford+Mustang+Front',
        rear: 'https://placehold.co/600x400.png?text=Ford+Mustang+Rear',
        side: 'https://placehold.co/600x400.png?text=Ford+Mustang+Side',
        topDown: 'https://placehold.co/600x400.png?text=Ford+Mustang+Top',
        wheel: 'https://placehold.co/600x400.png?text=Ford+Mustang+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Ford+Mustang+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Ford+Mustang+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Ford+Mustang+Console',
        seats: 'https://placehold.co/600x400.png?text=Ford+Mustang+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Ford+Mustang+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Ford+Mustang+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Ford+Mustang+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Ford+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Ford+Mustang+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Ford+Mustang+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Ford+Mustang+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Ford+Mustang+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Ford+Mustang+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Ford+Mustang+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Ford+Mustang+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Ford+Mustang+Night',
      },
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Blue',
    interiorColor: 'Black',
    drivetrain: 'RWD',
    mileage: 21000,
    seatingCapacity: 4,
    status: 'Sold',
    specs: {
      engine: '5.0L V8',
      horsepower: 480,
      fuelConsumption: '13.1L/100km',
      safetyRating: 4,
      dimensions: { length: 4788, width: 1915, height: 1379 },
    },
    features: ['Hộp số tự động 10 cấp', 'Bảng đồng hồ kỹ thuật số', 'Hệ thống giảm xóc MagneRide', 'Hệ thống ống xả van chủ động'],
    reviews: [
      { name: 'Ethan', rating: 4, comment: 'Tiếng gầm V8 gây nghiện. Giá trị tuyệt vời cho sức mạnh.' },
      { name: 'Fiona', rating: 4, comment: 'Lái vui, nhưng nội thất có thể tinh tế hơn.' },
    ],
  },
  {
    id: 4,
    brand: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    price: 780000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+RAV4+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+RAV4+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Front',
        rear: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Rear',
        side: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Side',
        topDown: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Top',
        wheel: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Console',
        seats: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Toyota+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Toyota+RAV4+Night',
      },
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 35000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 219,
      fuelConsumption: '5.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4600, width: 1855, height: 1685 },
    },
    features: ['Dẫn động 4 bánh toàn thời gian', 'Gói an toàn Toyota Safety Sense 2.5', 'Kết nối Apple CarPlay', 'Cảnh báo điểm mù'],
    reviews: [
      { name: 'George', rating: 5, comment: 'Tiết kiệm nhiên liệu đáng kinh ngạc và rất thiết thực cho gia đình tôi.' },
      { name: 'Hannah', rating: 4, comment: 'SUV vững chắc, đáng tin cậy. Chỉ mong nó nhanh hơn một chút.' },
    ],
  },
  {
    id: 5,
    brand: 'BMW',
    model: 'M3',
    year: 2024,
    price: 1900000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+M3+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+M3+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=BMW+M3+Front',
        rear: 'https://placehold.co/600x400.png?text=BMW+M3+Rear',
        side: 'https://placehold.co/600x400.png?text=BMW+M3+Side',
        topDown: 'https://placehold.co/600x400.png?text=BMW+M3+Top',
        wheel: 'https://placehold.co/600x400.png?text=BMW+M3+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=BMW+M3+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=BMW+M3+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=BMW+M3+Console',
        seats: 'https://placehold.co/600x400.png?text=BMW+M3+Seats',
        trunk: 'https://placehold.co/600x400.png?text=BMW+M3+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=BMW+M3+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=BMW+M3+Taillight',
        logo: 'https://placehold.co/600x400.png?text=BMW+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=BMW+M3+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=BMW+M3+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=BMW+M3+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=BMW+M3+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=BMW+M3+Sunroof',
        key: 'https://placehold.co/600x400.png?text=BMW+M3+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=BMW+M3+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=BMW+M3+Night',
      },
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Sedan',
    exteriorColor: 'Green',
    interiorColor: 'Tan',
    drivetrain: 'RWD',
    mileage: 8900,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L M TwinPower Turbo inline 6-cylinder',
      horsepower: 473,
      fuelConsumption: '12.3L/100km',
      safetyRating: 5,
      dimensions: { length: 4794, width: 1903, height: 1437 },
    },
    features: ['Vi sai M Sport', 'Hệ thống treo thích ứng M', 'Mui xe bằng sợi carbon', 'Ghế thể thao M'],
    reviews: [
      { name: 'Ian', rating: 5, comment: 'Sự pha trộn hoàn hảo giữa xe thể thao và xe đi hàng ngày.' },
      { name: 'Jane', rating: 5, comment: 'Khả năng xử lý sắc như dao cạo. Một niềm vui khi lái trên mọi con đường.' },
    ],
  },
  {
    id: 6,
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 1120000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Front',
        rear: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Rear',
        side: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Side',
        topDown: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Top',
        wheel: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Console',
        seats: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Honda+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Honda+Civic+Type+R+Night',
      },
    },
    logo: '/logos/honda.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Compact',
    exteriorColor: 'Red',
    interiorColor: 'Red',
    drivetrain: 'FWD',
    mileage: 15200,
    seatingCapacity: 4,
    status: 'Sold',
    specs: {
      engine: '2.0L Turbocharged VTEC',
      horsepower: 315,
      fuelConsumption: '9.8L/100km',
      safetyRating: 5,
      dimensions: { length: 4594, width: 1890, height: 1407 },
    },
    features: ['Hộp số sàn 6 cấp', 'Hệ thống LogR Datalogger', 'Phanh hiệu suất cao Brembo', 'Cánh gió thể thao'],
    reviews: [
      { name: 'Kevin', rating: 5, comment: 'Chiếc xe dẫn động cầu trước tốt nhất trên thị trường. Chấm hết.' },
      { name: 'Laura', rating: 4, comment: 'Cực kỳ thú vị, nhưng kiểu dáng hơi quá hầm hố đối với tôi.' },
    ],
  },
    {
    id: 7,
    brand: 'Audi',
    model: 'R8',
    year: 2023,
    price: 3965000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+R8+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+R8+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Audi+R8+Front',
        rear: 'https://placehold.co/600x400.png?text=Audi+R8+Rear',
        side: 'https://placehold.co/600x400.png?text=Audi+R8+Side',
        topDown: 'https://placehold.co/600x400.png?text=Audi+R8+Top',
        wheel: 'https://placehold.co/600x400.png?text=Audi+R8+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Audi+R8+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Audi+R8+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Audi+R8+Console',
        seats: 'https://placehold.co/600x400.png?text=Audi+R8+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Audi+R8+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Audi+R8+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Audi+R8+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Audi+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Audi+R8+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Audi+R8+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Audi+R8+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Audi+R8+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Audi+R8+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Audi+R8+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Audi+R8+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Audi+R8+Night',
      },
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 9500,
    seatingCapacity: 2,
    status: 'Available',
    specs: {
      engine: '5.2L V10',
      horsepower: 562,
      fuelConsumption: '13.8L/100km',
      safetyRating: 4,
      dimensions: { length: 4429, width: 1940, height: 1236 },
    },
    features: ['Dẫn động 4 bánh Quattro', 'Buồng lái ảo Virtual Cockpit', 'Hệ thống âm thanh Bang & Olufsen', 'Ốp nội thất sợi carbon'],
    reviews: [
      { name: 'Mike', rating: 5, comment: 'Âm thanh V10 say đắm. Một siêu xe bạn có thể lái hàng ngày.' },
      { name: 'Nina', rating: 5, comment: 'Vẻ ngoài tuyệt đẹp và hiệu suất kinh ngạc. Thu hút mọi ánh nhìn.' },
    ],
  },
  {
    id: 8,
    brand: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2024,
    price: 1135000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Front',
        rear: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Rear',
        side: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Side',
        topDown: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Top',
        wheel: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Console',
        seats: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Jeep+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Jeep+Wrangler+Night',
      },
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Brown',
    drivetrain: '4WD',
    mileage: 45000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: '3.0L V6 Turbodiesel',
      horsepower: 285,
      fuelConsumption: '9.4L/100km',
      safetyRating: 3,
      dimensions: { length: 4882, width: 1894, height: 1838 },
    },
    features: ['Hệ thống 4x4 Rock-Trac', 'Khóa vi sai điện tử', 'Thanh cân bằng điện tử', 'Cửa và mui có thể tháo rời'],
    reviews: [
      { name: 'Oscar', rating: 5, comment: 'Không thể ngăn cản khi off-road. Nó có thể đi bất cứ đâu.' },
      { name: 'Penny', rating: 3, comment: 'Tuyệt vời trên đường mòn, nhưng rất xóc và ồn trên đường cao tốc.' },
    ],
  },
  {
    id: 9,
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 1150000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+3+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+3+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Front',
        rear: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Rear',
        side: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Side',
        topDown: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Top',
        wheel: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Console',
        seats: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Tesla+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Tesla+Model+3+Night',
      },
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Blue',
    interiorColor: 'White',
    drivetrain: 'RWD',
    mileage: 22000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 283,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4694, width: 1849, height: 1443 },
    },
    features: ['Màn hình cảm ứng 15"', 'Cửa sổ trời toàn cảnh', 'Sạc không dây', 'Ghế da Vegan'],
    reviews: [
      { name: 'Quang', rating: 5, comment: 'Chiếc xe điện tuyệt vời cho việc đi lại hàng ngày. Rất nhanh và hiệu quả.' },
    ],
  },
  {
    id: 10,
    brand: 'Tesla',
    model: 'Model X',
    year: 2022,
    price: 2450000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+X+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+X+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Front',
        rear: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Rear',
        side: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Side',
        topDown: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Top',
        wheel: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Console',
        seats: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Tesla+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Tesla+Model+X+Night',
      },
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'White',
    drivetrain: 'AWD',
    mileage: 18000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: 'Electric',
      horsepower: 670,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 5037, width: 1999, height: 1684 },
    },
    features: ['Cửa cánh chim Falcon Wing', 'Hệ thống lái tự động Autopilot', 'Màn hình cảm ứng 17"', 'Kính chắn gió panorama'],
    reviews: [
      { name: 'Mai', rating: 5, comment: 'Cửa Falcon Wing thật ấn tượng. Rất nhiều không gian cho gia đình.' },
    ],
  },
  {
    id: 11,
    brand: 'Tesla',
    model: 'Model Y',
    year: 2023,
    price: 1380000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Front',
        rear: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Rear',
        side: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Side',
        topDown: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Top',
        wheel: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Console',
        seats: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Tesla+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Tesla+Model+Y+Night',
      },
    },
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 14000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: 'Electric',
      horsepower: 384,
      fuelConsumption: 'N/A (Electric)',
      safetyRating: 5,
      dimensions: { length: 4751, width: 1921, height: 1624 },
    },
    features: ['Không gian chứa đồ lớn', 'Hiệu suất cao', 'Cửa sổ trời toàn cảnh', 'Bơm nhiệt hiệu quả'],
    reviews: [
      { name: 'Anh', rating: 5, comment: 'Sự kết hợp hoàn hảo giữa hiệu suất của Model 3 và tính thực dụng của một chiếc SUV.' },
    ],
  },
  {
    id: 12,
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2022,
    price: 2950000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Front',
        rear: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Rear',
        side: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Side',
        topDown: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Top',
        wheel: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Console',
        seats: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Porsche+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Porsche+Cayenne+Night',
      },
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 28000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L V6 Turbo + Electric Motor',
      horsepower: 455,
      fuelConsumption: '3.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4930, width: 1983, height: 1678 },
    },
    features: ['Hệ thống treo khí nén', 'Porsche Communication Management (PCM)', 'Nội thất da cao cấp', 'Chế độ lái E-Power'],
    reviews: [
      { name: 'Bảo', rating: 5, comment: 'Một chiếc SUV với DNA của xe thể thao. Cảm giác lái tuyệt vời và sang trọng.' },
    ],
  },
  {
    id: 13,
    brand: 'Porsche',
    model: 'Panamera 4',
    year: 2021,
    price: 2680000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Panamera+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Panamera+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Front',
        rear: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Rear',
        side: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Side',
        topDown: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Top',
        wheel: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Console',
        seats: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Porsche+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Porsche+Panamera+Night',
      },
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 32000,
    seatingCapacity: 4,
    status: 'Available',
    specs: {
      engine: '2.9L Twin-Turbo V6',
      horsepower: 325,
      fuelConsumption: '10.5L/100km',
      safetyRating: 5,
      dimensions: { length: 5049, width: 1937, height: 1423 },
    },
    features: ['Nội thất sang trọng', 'Khả năng vận hành thể thao', 'Cánh gió sau thích ứng', 'Hệ thống âm thanh Bose'],
    reviews: [
      { name: 'Châu', rating: 5, comment: 'Chiếc sedan sang trọng tốt nhất tôi từng lái. Vừa thoải mái vừa thể thao.' },
    ],
  },
  {
    id: 14,
    brand: 'Porsche',
    model: 'Macan',
    year: 2023,
    price: 1980000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Macan+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Porsche+Macan+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Porsche+Macan+Front',
        rear: 'https://placehold.co/600x400.png?text=Porsche+Macan+Rear',
        side: 'https://placehold.co/600x400.png?text=Porsche+Macan+Side',
        topDown: 'https://placehold.co/600x400.png?text=Porsche+Macan+Top',
        wheel: 'https://placehold.co/600x400.png?text=Porsche+Macan+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Porsche+Macan+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Porsche+Macan+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Porsche+Macan+Console',
        seats: 'https://placehold.co/600x400.png?text=Porsche+Macan+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Porsche+Macan+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Porsche+Macan+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Porsche+Macan+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Porsche+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Porsche+Macan+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Porsche+Macan+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Porsche+Macan+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Porsche+Macan+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Porsche+Macan+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Porsche+Macan+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Porsche+Macan+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Porsche+Macan+Night',
      },
    },
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Blue',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 11000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L Turbo I4',
      horsepower: 261,
      fuelConsumption: '9.2L/100km',
      safetyRating: 5,
      dimensions: { length: 4726, width: 1922, height: 1621 },
    },
    features: ['Hộp số PDK 7 cấp', 'Hệ thống dẫn động 4 bánh toàn thời gian', 'Thiết kế nhỏ gọn, linh hoạt', 'Màn hình cảm ứng 10.9"'],
    reviews: [
      { name: 'Dũng', rating: 4, comment: 'Một chiếc SUV nhỏ gọn tuyệt vời, cảm giác lái rất giống xe Porsche. Hàng ghế sau hơi chật.' },
    ],
  },
  {
    id: 15,
    brand: 'Ford',
    model: 'Explorer',
    year: 2022,
    price: 1850000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Explorer+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Explorer+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Ford+Explorer+Front',
        rear: 'https://placehold.co/600x400.png?text=Ford+Explorer+Rear',
        side: 'https://placehold.co/600x400.png?text=Ford+Explorer+Side',
        topDown: 'https://placehold.co/600x400.png?text=Ford+Explorer+Top',
        wheel: 'https://placehold.co/600x400.png?text=Ford+Explorer+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Ford+Explorer+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Ford+Explorer+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Ford+Explorer+Console',
        seats: 'https://placehold.co/600x400.png?text=Ford+Explorer+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Ford+Explorer+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Ford+Explorer+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Ford+Explorer+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Ford+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Ford+Explorer+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Ford+Explorer+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Ford+Explorer+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Ford+Explorer+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Ford+Explorer+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Ford+Explorer+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Ford+Explorer+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Ford+Explorer+Night',
      },
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 45000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: '2.3L EcoBoost I4',
      horsepower: 300,
      fuelConsumption: '10.2L/100km',
      safetyRating: 5,
      dimensions: { length: 5049, width: 2004, height: 1778 },
    },
    features: ['7 chỗ ngồi rộng rãi', 'Hệ thống thông tin giải trí SYNC 3', 'Gói an toàn Co-Pilot360', 'Cửa sổ trời panorama'],
    reviews: [
      { name: 'Giang', rating: 4, comment: 'SUV gia đình tuyệt vời, nhiều không gian và công nghệ.' },
    ],
  },
  {
    id: 16,
    brand: 'Ford',
    model: 'Bronco',
    year: 2023,
    price: 1550000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Bronco+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Bronco+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Ford+Bronco+Front',
        rear: 'https://placehold.co/600x400.png?text=Ford+Bronco+Rear',
        side: 'https://placehold.co/600x400.png?text=Ford+Bronco+Side',
        topDown: 'https://placehold.co/600x400.png?text=Ford+Bronco+Top',
        wheel: 'https://placehold.co/600x400.png?text=Ford+Bronco+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Ford+Bronco+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Ford+Bronco+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Ford+Bronco+Console',
        seats: 'https://placehold.co/600x400.png?text=Ford+Bronco+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Ford+Bronco+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Ford+Bronco+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Ford+Bronco+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Ford+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Ford+Bronco+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Ford+Bronco+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Ford+Bronco+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Ford+Bronco+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Ford+Bronco+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Ford+Bronco+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Ford+Bronco+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Ford+Bronco+Night',
      },
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Silver',
    interiorColor: 'Gray',
    drivetrain: '4WD',
    mileage: 15000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.7L EcoBoost V6',
      horsepower: 330,
      fuelConsumption: '11.8L/100km',
      safetyRating: 4,
      dimensions: { length: 4811, width: 1928, height: 1852 },
    },
    features: ['Khả năng off-road vượt trội', 'Cửa và mui có thể tháo rời', 'Hệ thống G.O.A.T. Modes', 'Nội thất chống nước'],
    reviews: [
      { name: 'Huy', rating: 5, comment: 'Vua off-road đã trở lại! Vui nhộn và cực kỳ có năng lực.' },
    ],
  },
  {
    id: 17,
    brand: 'Ford',
    model: 'Focus',
    year: 2018,
    price: 480000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Focus+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Ford+Focus+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Ford+Focus+Front',
        rear: 'https://placehold.co/600x400.png?text=Ford+Focus+Rear',
        side: 'https://placehold.co/600x400.png?text=Ford+Focus+Side',
        topDown: 'https://placehold.co/600x400.png?text=Ford+Focus+Top',
        wheel: 'https://placehold.co/600x400.png?text=Ford+Focus+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Ford+Focus+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Ford+Focus+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Ford+Focus+Console',
        seats: 'https://placehold.co/600x400.png?text=Ford+Focus+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Ford+Focus+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Ford+Focus+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Ford+Focus+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Ford+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Ford+Focus+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Ford+Focus+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Ford+Focus+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Ford+Focus+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Ford+Focus+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Ford+Focus+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Ford+Focus+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Ford+Focus+Night',
      },
    },
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 65000,
    seatingCapacity: 5,
    status: 'Sold',
    specs: {
      engine: '1.5L EcoBoost',
      horsepower: 180,
      fuelConsumption: '7.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4378, width: 1825, height: 1454 },
    },
    features: ['Cảm giác lái thú vị', 'Tiết kiệm nhiên liệu', 'Hệ thống thông tin giải trí SYNC', 'Thiết kế nhỏ gọn'],
    reviews: [
      { name: 'Khánh', rating: 4, comment: 'Một chiếc xe nhỏ tuyệt vời để đi trong thành phố, cảm giác lái chắc chắn.' },
    ],
  },
  {
    id: 18,
    brand: 'Toyota',
    model: 'Camry Hybrid',
    year: 2022,
    price: 950000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Camry+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Camry+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Toyota+Camry+Front',
        rear: 'https://placehold.co/600x400.png?text=Toyota+Camry+Rear',
        side: 'https://placehold.co/600x400.png?text=Toyota+Camry+Side',
        topDown: 'https://placehold.co/600x400.png?text=Toyota+Camry+Top',
        wheel: 'https://placehold.co/600x400.png?text=Toyota+Camry+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Toyota+Camry+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Toyota+Camry+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Toyota+Camry+Console',
        seats: 'https://placehold.co/600x400.png?text=Toyota+Camry+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Toyota+Camry+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Toyota+Camry+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Toyota+Camry+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Toyota+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Toyota+Camry+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Toyota+Camry+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Toyota+Camry+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Toyota+Camry+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Toyota+Camry+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Toyota+Camry+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Toyota+Camry+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Toyota+Camry+Night',
      },
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Black',
    interiorColor: 'Beige',
    drivetrain: 'FWD',
    mileage: 38000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 208,
      fuelConsumption: '5.1L/100km',
      safetyRating: 5,
      dimensions: { length: 4885, width: 1840, height: 1445 },
    },
    features: ['Độ tin cậy cao', 'Tiết kiệm nhiên liệu xuất sắc', 'Nội thất rộng rãi', 'Gói an toàn Toyota Safety Sense'],
    reviews: [
      { name: 'Linh', rating: 5, comment: 'Chiếc xe hoàn hảo. Đáng tin cậy, thoải mái và tiết kiệm nhiên liệu.' },
    ],
  },
  {
    id: 19,
    brand: 'Toyota',
    model: 'Corolla',
    year: 2021,
    price: 620000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Corolla+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Corolla+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Front',
        rear: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Rear',
        side: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Side',
        topDown: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Top',
        wheel: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Console',
        seats: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Toyota+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Toyota+Corolla+Night',
      },
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'Blue',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 55000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.8L 4-Cylinder',
      horsepower: 139,
      fuelConsumption: '7.3L/100km',
      safetyRating: 5,
      dimensions: { length: 4630, width: 1780, height: 1435 },
    },
    features: ['Độ bền bỉ', 'Giữ giá', 'Chi phí vận hành thấp', 'Trang bị an toàn tiêu chuẩn'],
    reviews: [
      { name: 'Nam', rating: 4, comment: 'Không có gì thú vị, nhưng nó hoàn thành công việc một cách hoàn hảo và sẽ không làm bạn thất vọng.' },
    ],
  },
  {
    id: 20,
    brand: 'Toyota',
    model: 'Highlander',
    year: 2023,
    price: 1750000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Highlander+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Toyota+Highlander+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Front',
        rear: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Rear',
        side: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Side',
        topDown: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Top',
        wheel: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Console',
        seats: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Toyota+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Toyota+Highlander+Night',
      },
    },
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 25000,
    seatingCapacity: 8,
    status: 'Available',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 243,
      fuelConsumption: '6.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4950, width: 1930, height: 1730 },
    },
    features: ['3 hàng ghế', 'Nội thất chất lượng cao', 'Hệ thống giải trí cho hàng ghế sau', 'Cửa sổ trời'],
    reviews: [
      { name: 'Oanh', rating: 5, comment: 'SUV 3 hàng ghế tuyệt vời. Rất nhiều không gian và cực kỳ tiết kiệm nhiên liệu.' },
    ],
  },
  {
    id: 21,
    brand: 'BMW',
    model: 'X5',
    year: 2022,
    price: 2400000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+X5+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+X5+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=BMW+X5+Front',
        rear: 'https://placehold.co/600x400.png?text=BMW+X5+Rear',
        side: 'https://placehold.co/600x400.png?text=BMW+X5+Side',
        topDown: 'https://placehold.co/600x400.png?text=BMW+X5+Top',
        wheel: 'https://placehold.co/600x400.png?text=BMW+X5+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=BMW+X5+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=BMW+X5+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=BMW+X5+Console',
        seats: 'https://placehold.co/600x400.png?text=BMW+X5+Seats',
        trunk: 'https://placehold.co/600x400.png?text=BMW+X5+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=BMW+X5+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=BMW+X5+Taillight',
        logo: 'https://placehold.co/600x400.png?text=BMW+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=BMW+X5+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=BMW+X5+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=BMW+X5+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=BMW+X5+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=BMW+X5+Sunroof',
        key: 'https://placehold.co/600x400.png?text=BMW+X5+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=BMW+X5+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=BMW+X5+Night',
      },
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'Tan',
    drivetrain: 'AWD',
    mileage: 48000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.0L Inline 6-cylinder Turbodiesel',
      horsepower: 282,
      fuelConsumption: '7.0L/100km',
      safetyRating: 5,
      dimensions: { length: 4922, width: 2004, height: 1745 },
    },
    features: ['Hệ thống iDrive 7.0', 'Cửa sổ trời panorama Sky Lounge', 'Hệ thống treo khí nén thích ứng', 'Hệ thống hỗ trợ đỗ xe'],
    reviews: [
      { name: 'Phú', rating: 5, comment: 'Sang trọng, mạnh mẽ và cảm giác lái tuyệt vời. Một chiếc SUV hoàn hảo.' },
    ],
  },
  {
    id: 22,
    brand: 'BMW',
    model: '330i',
    year: 2023,
    price: 1450000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+330i+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+330i+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=BMW+330i+Front',
        rear: 'https://placehold.co/600x400.png?text=BMW+330i+Rear',
        side: 'https://placehold.co/600x400.png?text=BMW+330i+Side',
        topDown: 'https://placehold.co/600x400.png?text=BMW+330i+Top',
        wheel: 'https://placehold.co/600x400.png?text=BMW+330i+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=BMW+330i+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=BMW+330i+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=BMW+330i+Console',
        seats: 'https://placehold.co/600x400.png?text=BMW+330i+Seats',
        trunk: 'https://placehold.co/600x400.png?text=BMW+330i+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=BMW+330i+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=BMW+330i+Taillight',
        logo: 'https://placehold.co/600x400.png?text=BMW+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=BMW+330i+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=BMW+330i+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=BMW+330i+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=BMW+330i+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=BMW+330i+Sunroof',
        key: 'https://placehold.co/600x400.png?text=BMW+330i+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=BMW+330i+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=BMW+330i+Night',
      },
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Red',
    drivetrain: 'RWD',
    mileage: 21000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L TwinPower Turbo I4',
      horsepower: 255,
      fuelConsumption: '7.1L/100km',
      safetyRating: 5,
      dimensions: { length: 4713, width: 1827, height: 1440 },
    },
    features: ['Khung gầm thể thao', 'Phân bổ trọng lượng 50/50', 'Hệ thống Live Cockpit Professional', 'Đèn viền nội thất'],
    reviews: [
      { name: 'Quỳnh', rating: 5, comment: 'Chuẩn mực của dòng sedan thể thao. Cảm giác lái vô cùng phấn khích.' },
    ],
  },
  {
    id: 23,
    brand: 'BMW',
    model: 'Z4',
    year: 2021,
    price: 1750000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+Z4+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=BMW+Z4+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=BMW+Z4+Front',
        rear: 'https://placehold.co/600x400.png?text=BMW+Z4+Rear',
        side: 'https://placehold.co/600x400.png?text=BMW+Z4+Side',
        topDown: 'https://placehold.co/600x400.png?text=BMW+Z4+Top',
        wheel: 'https://placehold.co/600x400.png?text=BMW+Z4+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=BMW+Z4+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=BMW+Z4+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=BMW+Z4+Console',
        seats: 'https://placehold.co/600x400.png?text=BMW+Z4+Seats',
        trunk: 'https://placehold.co/600x400.png?text=BMW+Z4+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=BMW+Z4+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=BMW+Z4+Taillight',
        logo: 'https://placehold.co/600x400.png?text=BMW+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=BMW+Z4+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=BMW+Z4+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=BMW+Z4+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=BMW+Z4+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=BMW+Z4+Sunroof',
        key: 'https://placehold.co/600x400.png?text=BMW+Z4+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=BMW+Z4+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=BMW+Z4+Night',
      },
    },
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'RWD',
    mileage: 19000,
    seatingCapacity: 2,
    status: 'Sold',
    specs: {
      engine: '3.0L M TwinPower Turbo inline 6-cylinder',
      horsepower: 382,
      fuelConsumption: '9.0L/100km',
      safetyRating: 4,
      dimensions: { length: 4324, width: 1864, height: 1304 },
    },
    features: ['Mui mềm có thể đóng/mở nhanh', 'Thiết kế roadster cổ điển', 'Hiệu suất mạnh mẽ', 'Ghế thể thao'],
    reviews: [
      { name: 'Sơn', rating: 5, comment: 'Một chiếc roadster tuyệt vời để tận hưởng những ngày đẹp trời. Rất vui khi lái.' },
    ],
  },
  {
    id: 24,
    brand: 'Honda',
    model: 'CR-V Hybrid',
    year: 2023,
    price: 980000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+CR-V+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+CR-V+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Honda+CR-V+Front',
        rear: 'https://placehold.co/600x400.png?text=Honda+CR-V+Rear',
        side: 'https://placehold.co/600x400.png?text=Honda+CR-V+Side',
        topDown: 'https://placehold.co/600x400.png?text=Honda+CR-V+Top',
        wheel: 'https://placehold.co/600x400.png?text=Honda+CR-V+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Honda+CR-V+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Honda+CR-V+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Honda+CR-V+Console',
        seats: 'https://placehold.co/600x400.png?text=Honda+CR-V+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Honda+CR-V+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Honda+CR-V+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Honda+CR-V+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Honda+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Honda+CR-V+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Honda+CR-V+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Honda+CR-V+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Honda+CR-V+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Honda+CR-V+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Honda+CR-V+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Honda+CR-V+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Honda+CR-V+Night',
      },
    },
    logo: '/logos/honda.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'AWD',
    mileage: 26000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L 4-Cylinder Hybrid',
      horsepower: 204,
      fuelConsumption: '6.4L/100km',
      safetyRating: 5,
      dimensions: { length: 4694, width: 1866, height: 1681 },
    },
    features: ['Gói an toàn Honda Sensing', 'Nội thất rộng rãi', 'Tiết kiệm nhiên liệu', 'Hệ thống âm thanh Bose'],
    reviews: [
      { name: 'Tâm', rating: 5, comment: 'Một chiếc SUV rất thực dụng và đáng tin cậy. Hệ thống hybrid hoạt động mượt mà.' },
    ],
  },
  {
    id: 25,
    brand: 'Honda',
    model: 'Accord',
    year: 2022,
    price: 890000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+Accord+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+Accord+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Honda+Accord+Front',
        rear: 'https://placehold.co/600x400.png?text=Honda+Accord+Rear',
        side: 'https://placehold.co/600x400.png?text=Honda+Accord+Side',
        topDown: 'https://placehold.co/600x400.png?text=Honda+Accord+Top',
        wheel: 'https://placehold.co/600x400.png?text=Honda+Accord+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Honda+Accord+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Honda+Accord+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Honda+Accord+Console',
        seats: 'https://placehold.co/600x400.png?text=Honda+Accord+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Honda+Accord+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Honda+Accord+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Honda+Accord+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Honda+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Honda+Accord+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Honda+Accord+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Honda+Accord+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Honda+Accord+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Honda+Accord+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Honda+Accord+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Honda+Accord+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Honda+Accord+Night',
      },
    },
    logo: '/logos/honda.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Gray',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 41000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L 4-Cylinder Hybrid',
      horsepower: 204,
      fuelConsumption: '5.0L/100km',
      safetyRating: 5,
      dimensions: { length: 4971, width: 1862, height: 1450 },
    },
    features: ['Cảm giác lái thú vị', 'Thiết kế fastback', 'Nội thất cao cấp', 'Màn hình cảm ứng 12.3"'],
    reviews: [
      { name: 'Thành', rating: 4, comment: 'Một trong những chiếc sedan cỡ trung tốt nhất. Rộng rãi, hiệu quả và lái hay.' },
    ],
  },
  {
    id: 26,
    brand: 'Honda',
    model: 'HR-V',
    year: 2023,
    price: 720000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+HR-V+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Honda+HR-V+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Honda+HR-V+Front',
        rear: 'https://placehold.co/600x400.png?text=Honda+HR-V+Rear',
        side: 'https://placehold.co/600x400.png?text=Honda+HR-V+Side',
        topDown: 'https://placehold.co/600x400.png?text=Honda+HR-V+Top',
        wheel: 'https://placehold.co/600x400.png?text=Honda+HR-V+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Honda+HR-V+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Honda+HR-V+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Honda+HR-V+Console',
        seats: 'https://placehold.co/600x400.png?text=Honda+HR-V+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Honda+HR-V+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Honda+HR-V+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Honda+HR-V+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Honda+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Honda+HR-V+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Honda+HR-V+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Honda+HR-V+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Honda+HR-V+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Honda+HR-V+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Honda+HR-V+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Honda+HR-V+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Honda+HR-V+Night',
      },
    },
    logo: '/logos/honda.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 19000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.5L Turbo I4',
      horsepower: 177,
      fuelConsumption: '6.7L/100km',
      safetyRating: 5,
      dimensions: { length: 4385, width: 1790, height: 1590 },
    },
    features: ['Thiết kế thể thao', 'Ghế Magic Seat linh hoạt', 'Gói an toàn Honda Sensing', 'Cửa sổ trời'],
    reviews: [
      { name: 'Trang', rating: 4, comment: 'SUV nhỏ gọn tuyệt vời cho thành phố. Rất linh hoạt.' },
    ],
  },
  {
    id: 27,
    brand: 'Audi',
    model: 'Q7',
    year: 2021,
    price: 2150000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+Q7+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+Q7+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Audi+Q7+Front',
        rear: 'https://placehold.co/600x400.png?text=Audi+Q7+Rear',
        side: 'https://placehold.co/600x400.png?text=Audi+Q7+Side',
        topDown: 'https://placehold.co/600x400.png?text=Audi+Q7+Top',
        wheel: 'https://placehold.co/600x400.png?text=Audi+Q7+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Audi+Q7+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Audi+Q7+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Audi+Q7+Console',
        seats: 'https://placehold.co/600x400.png?text=Audi+Q7+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Audi+Q7+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Audi+Q7+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Audi+Q7+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Audi+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Audi+Q7+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Audi+Q7+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Audi+Q7+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Audi+Q7+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Audi+Q7+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Audi+Q7+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Audi+Q7+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Audi+Q7+Night',
      },
    },
    logo: '/logos/audi.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Blue',
    interiorColor: 'Beige',
    drivetrain: 'AWD',
    mileage: 60000,
    seatingCapacity: 7,
    status: 'Available',
    specs: {
      engine: '3.0L V6 TDI',
      horsepower: 286,
      fuelConsumption: '8.0L/100km',
      safetyRating: 5,
      dimensions: { length: 5063, width: 1970, height: 1741 },
    },
    features: ['Nội thất công nghệ cao', 'Buồng lái ảo Virtual Cockpit', 'Hệ thống treo khí nén', '3 hàng ghế'],
    reviews: [
      { name: 'Việt', rating: 5, comment: 'Chiếc SUV gia đình sang trọng và thoải mái. Công nghệ rất ấn tượng.' },
    ],
  },
  {
    id: 28,
    brand: 'Audi',
    model: 'A6',
    year: 2022,
    price: 1950000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+A6+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+A6+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Audi+A6+Front',
        rear: 'https://placehold.co/600x400.png?text=Audi+A6+Rear',
        side: 'https://placehold.co/600x400.png?text=Audi+A6+Side',
        topDown: 'https://placehold.co/600x400.png?text=Audi+A6+Top',
        wheel: 'https://placehold.co/600x400.png?text=Audi+A6+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Audi+A6+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Audi+A6+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Audi+A6+Console',
        seats: 'https://placehold.co/600x400.png?text=Audi+A6+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Audi+A6+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Audi+A6+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Audi+A6+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Audi+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Audi+A6+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Audi+A6+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Audi+A6+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Audi+A6+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Audi+A6+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Audi+A6+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Audi+A6+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Audi+A6+Night',
      },
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'Silver',
    interiorColor: 'Brown',
    drivetrain: 'AWD',
    mileage: 33000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.0L TFSI I4',
      horsepower: 248,
      fuelConsumption: '7.6L/100km',
      safetyRating: 5,
      dimensions: { length: 4939, width: 1886, height: 1457 },
    },
    features: ['Hệ thống MMI hai màn hình cảm ứng', 'Đèn Matrix LED', 'Nội thất ốp gỗ', 'Hệ thống âm thanh cao cấp'],
    reviews: [
      { name: 'Xuân', rating: 5, comment: 'Một chiếc sedan hạng sang tinh tế. Vận hành êm ái và nội thất tuyệt đẹp.' },
    ],
  },
  {
    id: 29,
    brand: 'Audi',
    model: 'A3',
    year: 2020,
    price: 1100000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+A3+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Audi+A3+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Audi+A3+Front',
        rear: 'https://placehold.co/600x400.png?text=Audi+A3+Rear',
        side: 'https://placehold.co/600x400.png?text=Audi+A3+Side',
        topDown: 'https://placehold.co/600x400.png?text=Audi+A3+Top',
        wheel: 'https://placehold.co/600x400.png?text=Audi+A3+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Audi+A3+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Audi+A3+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Audi+A3+Console',
        seats: 'https://placehold.co/600x400.png?text=Audi+A3+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Audi+A3+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Audi+A3+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Audi+A3+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Audi+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Audi+A3+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Audi+A3+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Audi+A3+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Audi+A3+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Audi+A3+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Audi+A3+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Audi+A3+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Audi+A3+Night',
      },
    },
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Compact',
    exteriorColor: 'White',
    interiorColor: 'Black',
    drivetrain: 'FWD',
    mileage: 42000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.4L TFSI I4',
      horsepower: 150,
      fuelConsumption: '6.5L/100km',
      safetyRating: 5,
      dimensions: { length: 4458, width: 1796, height: 1416 },
    },
    features: ['Buồng lái ảo Virtual Cockpit', 'Thiết kế nhỏ gọn, sang trọng', 'Cửa sổ trời', 'Đèn viền nội thất'],
    reviews: [
      { name: 'Yến', rating: 4, comment: 'Chiếc xe sang cỡ nhỏ tuyệt vời. Hoàn hảo cho việc đi lại trong thành phố.' },
    ],
  },
  {
    id: 30,
    brand: 'Jeep',
    model: 'Grand Cherokee',
    year: 2022,
    price: 2100000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Front',
        rear: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Rear',
        side: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Side',
        topDown: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Top',
        wheel: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Console',
        seats: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Jeep+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Jeep+Grand+Cherokee+Night',
      },
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Silver',
    interiorColor: 'Black',
    drivetrain: '4WD',
    mileage: 31000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '3.6L V6',
      horsepower: 293,
      fuelConsumption: '10.7L/100km',
      safetyRating: 5,
      dimensions: { length: 4914, width: 1968, height: 1799 },
    },
    features: ['Hệ thống 4x4 Quadra-Trac', 'Hệ thống treo khí nén Quadra-Lift', 'Nội thất cao cấp', 'Hệ thống Uconnect 5'],
    reviews: [
      { name: 'An', rating: 5, comment: 'Vừa sang trọng vừa có khả năng off-road. Sự kết hợp tốt nhất của cả hai thế giới.' },
    ],
  },
  {
    id: 31,
    brand: 'Jeep',
    model: 'Compass',
    year: 2021,
    price: 950000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Compass+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Compass+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Jeep+Compass+Front',
        rear: 'https://placehold.co/600x400.png?text=Jeep+Compass+Rear',
        side: 'https://placehold.co/600x400.png?text=Jeep+Compass+Side',
        topDown: 'https://placehold.co/600x400.png?text=Jeep+Compass+Top',
        wheel: 'https://placehold.co/600x400.png?text=Jeep+Compass+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Jeep+Compass+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Jeep+Compass+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Jeep+Compass+Console',
        seats: 'https://placehold.co/600x400.png?text=Jeep+Compass+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Jeep+Compass+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Jeep+Compass+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Jeep+Compass+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Jeep+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Jeep+Compass+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Jeep+Compass+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Jeep+Compass+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Jeep+Compass+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Jeep+Compass+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Jeep+Compass+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Jeep+Compass+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Jeep+Compass+Night',
      },
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Green',
    interiorColor: 'Black',
    drivetrain: '4WD',
    mileage: 40000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '2.4L I4',
      horsepower: 177,
      fuelConsumption: '9.4L/100km',
      safetyRating: 4,
      dimensions: { length: 4404, width: 1819, height: 1645 },
    },
    features: ['Hệ thống Selec-Terrain', 'Thiết kế đặc trưng của Jeep', 'Cửa sổ trời panorama', 'Màn hình cảm ứng 10.1"'],
    reviews: [
      { name: 'Bình', rating: 4, comment: 'Một chiếc SUV nhỏ gọn có năng lực, cảm giác chắc chắn và an toàn.' },
    ],
  },
  {
    id: 32,
    brand: 'Jeep',
    model: 'Renegade',
    year: 2020,
    price: 780000000,
    images: {
      exterior: {
        frontThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Renegade+3-4+Front',
        rearThreeQuarter: 'https://placehold.co/600x400.png?text=Jeep+Renegade+3-4+Rear',
        front: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Front',
        rear: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Rear',
        side: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Side',
        topDown: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Top',
        wheel: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Wheel',
      },
      interior: {
        dashboard: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Dashboard',
        dashboardCloseUp: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Cockpit',
        centerConsole: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Console',
        seats: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Seats',
        trunk: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Trunk',
      },
      details: {
        headlight: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Headlight',
        taillight: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Taillight',
        logo: 'https://placehold.co/600x400.png?text=Jeep+Logo',
        exhaust: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Exhaust',
        doorHandle: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Door+Handle',
        mirror: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Mirror',
        sensors: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Sensors',
        sunroof: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Sunroof',
        key: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Key',
      },
      dynamic: {
        rollingShot: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Rolling',
        nightShot: 'https://placehold.co/600x400.png?text=Jeep+Renegade+Night',
      },
    },
    logo: '/logos/jeep.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Red',
    interiorColor: 'Gray',
    drivetrain: '4WD',
    mileage: 45000,
    seatingCapacity: 5,
    status: 'Available',
    specs: {
      engine: '1.3L Turbo I4',
      horsepower: 177,
      fuelConsumption: '8.7L/100km',
      safetyRating: 4,
      dimensions: { length: 4232, width: 1805, height: 1689 },
    },
    features: ['Thiết kế cá tính', 'Cửa sổ trời My Sky', 'Khả năng off-road tốt trong phân khúc', 'Nhiều chi tiết thú vị'],
    reviews: [
      { name: 'Cường', rating: 4, comment: 'SUV nhỏ nhắn nhưng đầy cá tính. Lái trong thành phố rất vui.' },
    ],
  },
];
