import type { Car } from './types';

export const cars: Car[] = [
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 79990,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/tesla.svg',
    fuelType: 'Electric',
    transmission: 'Automatic',
    type: 'Sedan',
    exteriorColor: 'White',
    interiorColor: 'Black',
    specs: {
      engine: 'Electric',
      horsepower: 670,
      fuelEfficiency: '405 mi range',
      safetyRating: 5,
    },
    features: ['Autopilot', '17" Touchscreen', 'All-Wheel Drive', 'Premium Interior'],
    reviews: [
      { name: 'Alex', rating: 5, comment: 'Incredible speed and range. The future is here.' },
      { name: 'Beth', rating: 4, comment: 'Love the tech, but charging can be a hassle on road trips.' },
    ],
  },
  {
    id: 2,
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    price: 114400,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/porsche.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Silver',
    interiorColor: 'Red',
    specs: {
      engine: '3.0L Twin-Turbo Boxer 6',
      horsepower: 379,
      fuelEfficiency: '20 MPG Combined',
      safetyRating: 5,
    },
    features: ['Rear-Engine Layout', 'Porsche Active Suspension Management', 'Sport Chrono Package', 'Leather Interior'],
    reviews: [
      { name: 'Charlie', rating: 5, comment: 'The driving experience is unparalleled. A true driver\'s car.' },
      { name: 'Diana', rating: 5, comment: 'Iconic design and thrilling performance.' },
    ],
  },
  {
    id: 3,
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    price: 42495,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/ford.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Blue',
    interiorColor: 'Black',
    specs: {
      engine: '5.0L V8',
      horsepower: 480,
      fuelEfficiency: '18 MPG Combined',
      safetyRating: 4,
    },
    features: ['10-Speed Automatic', 'Digital Instrument Cluster', 'MagneRide Damping System', 'Active Valve Exhaust'],
    reviews: [
      { name: 'Ethan', rating: 4, comment: 'The V8 roar is addictive. Great value for the power.' },
      { name: 'Fiona', rating: 4, comment: 'Fun to drive, but the interior could be more refined.' },
    ],
  },
  {
    id: 4,
    brand: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    price: 31225,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/toyota.svg',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Beige',
    specs: {
      engine: '2.5L 4-Cylinder Hybrid',
      horsepower: 219,
      fuelEfficiency: '40 MPG Combined',
      safetyRating: 5,
    },
    features: ['All-Wheel Drive', 'Toyota Safety Sense 2.5', 'Apple CarPlay', 'Blind Spot Monitor'],
    reviews: [
      { name: 'George', rating: 5, comment: 'Amazingly fuel efficient and very practical for my family.' },
      { name: 'Hannah', rating: 4, comment: 'Solid, reliable SUV. Just wish it was a bit quicker.' },
    ],
  },
  {
    id: 5,
    brand: 'BMW',
    model: 'M3',
    year: 2024,
    price: 76000,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/bmw.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Sedan',
    exteriorColor: 'Green',
    interiorColor: 'Tan',
    specs: {
      engine: '3.0L M TwinPower Turbo inline 6-cylinder',
      horsepower: 473,
      fuelEfficiency: '19 MPG Combined',
      safetyRating: 5,
    },
    features: ['M Sport Differential', 'Adaptive M Suspension', 'Carbon Fiber Roof', 'M Sport Seats'],
    reviews: [
      { name: 'Ian', rating: 5, comment: 'The perfect blend of a sports car and a daily driver.' },
      { name: 'Jane', rating: 5, comment: 'The handling is razor-sharp. A joy to drive on any road.' },
    ],
  },
  {
    id: 6,
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 44795,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/honda.svg',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    type: 'Compact',
    exteriorColor: 'Red',
    interiorColor: 'Red',
    specs: {
      engine: '2.0L Turbocharged VTEC',
      horsepower: 315,
      fuelEfficiency: '24 MPG Combined',
      safetyRating: 5,
    },
    features: ['6-Speed Manual', 'LogR Datalogger', 'Brembo Brakes', 'High-Wing Spoiler'],
    reviews: [
      { name: 'Kevin', rating: 5, comment: 'The best front-wheel-drive car on the market. Period.' },
      { name: 'Laura', rating: 4, comment: 'Incredibly fun, but the styling is a bit too aggressive for me.' },
    ],
  },
    {
    id: 7,
    brand: 'Audi',
    model: 'R8',
    year: 2023,
    price: 158600,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/audi.svg',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    type: 'Coupe',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    specs: {
      engine: '5.2L V10',
      horsepower: 562,
      fuelEfficiency: '17 MPG Combined',
      safetyRating: 4,
    },
    features: ['Quattro All-Wheel Drive', 'Virtual Cockpit', 'Bang & Olufsen Sound System', 'Carbon Fiber Trim'],
    reviews: [
      { name: 'Mike', rating: 5, comment: 'The V10 sound is intoxicating. A supercar you can drive every day.' },
      { name: 'Nina', rating: 5, comment: 'Stunning looks and blistering performance. Turns heads everywhere.' },
    ],
  },
  {
    id: 8,
    brand: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2024,
    price: 45390,
    image: 'https://placehold.co/600x400.png',
    logo: '/logos/jeep.svg',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    exteriorColor: 'Gray',
    interiorColor: 'Brown',
    specs: {
      engine: '3.0L V6 Turbodiesel',
      horsepower: 285,
      fuelEfficiency: '25 MPG Combined',
      safetyRating: 3,
    },
    features: ['Rock-Trac 4x4 System', 'Electronic Locking Differentials', 'Sway Bar Disconnect', 'Removable Doors & Roof'],
    reviews: [
      { name: 'Oscar', rating: 5, comment: 'Unstoppable off-road. It can go anywhere.' },
      { name: 'Penny', rating: 3, comment: 'Amazing on the trails, but very rough and noisy on the highway.' },
    ],
  },
];
