
export interface Testimonial {
  quote: string;
  name: string;
  role: string;
  province: string;
  rating: number;
  date: string;
}

export const testimonials: Testimonial[] = [
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe ưng ý cho gia đình mình.",
    name: "Anh Hoàng Minh",
    role: "Khách hàng mua xe Toyota Camry",
    province: "Hà Nội",
    rating: 5,
    date: "15/05/2023",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Chị Thu Trang",
    role: "Khách hàng bán xe Mazda CX-5",
    province: "TP. Hồ Chí Minh",
    rating: 5,
    date: "22/11/2022",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe tại TimeCarsAuto.",
    name: "Anh Quốc Bảo",
    role: "Khách hàng mua xe Mercedes-Benz E-Class",
    province: "Đà Nẵng",
    rating: 5,
    date: "01/03/2024",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Minh Quân",
    role: "Khách hàng mua xe BMW X5",
    province: "Hải Phòng",
    rating: 5,
    date: "18/09/2023",
  },
  {
    quote: "Thủ tục mua bán xe nhanh gọn, minh bạch. TimeCarsAuto đã hỗ trợ tôi rất nhiều từ khâu chọn xe đến lúc hoàn tất giấy tờ. Sẽ quay lại trong tương lai.",
    name: "Chị Phương Anh",
    role: "Khách hàng bán xe Ford Explorer",
    province: "Bình Dương",
    rating: 5,
    date: "05/02/2023",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe nhận được. Rất khuyến khích!",
    name: "Anh Tuấn Kiệt",
    role: "Khách hàng mua xe Audi Q7",
    province: "Đồng Nai",
    rating: 5,
    date: "29/06/2024",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Chị Lan Anh",
    role: "Khách hàng mua xe Honda CR-V",
    province: "Cần Thơ",
    rating: 5,
    date: "11/08/2022",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Anh Bình An",
    role: "Khách hàng mua xe Lexus RX350",
    province: "Quảng Ninh",
    rating: 5,
    date: "03/12/2023",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Anh Văn Hùng",
    role: "Khách hàng mua xe VinFast Lux A2.0",
    province: "Thanh Hóa",
    rating: 5,
    date: "14/04/2022",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Mai Hương",
    role: "Khách hàng mua xe Hyundai Santa Fe",
    province: "Nghệ An",
    rating: 5,
    date: "25/01/2024",
  },
  {
    quote: "Chiếc Kia Seltos mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Đức Thắng",
    role: "Khách hàng mua xe Kia Seltos",
    province: "Hải Dương",
    rating: 4,
    date: "08/07/2023",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Chị Ngọc Bích",
    role: "Khách hàng bán xe Ford Ranger",
    province: "Hưng Yên",
    rating: 5,
    date: "19/10/2022",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Anh Quang Huy",
    role: "Khách hàng mua xe Toyota Vios",
    province: "Bắc Ninh",
    rating: 5,
    date: "02/06/2023",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Minh Đức",
    role: "Khách hàng mua xe Honda City",
    province: "Vĩnh Phúc",
    rating: 5,
    date: "13/03/2022",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Chị Thanh Tâm",
    role: "Khách hàng mua xe Mitsubishi Xpander",
    province: "Thái Nguyên",
    rating: 5,
    date: "27/08/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Porsche Macan ưng ý cho gia đình mình.",
    name: "Anh Bùi Long",
    role: "Khách hàng mua xe Porsche Macan",
    province: "Tuyên Quang",
    rating: 5,
    date: "10/05/2024",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Anh Lý Quang",
    role: "Khách hàng mua xe BMW 320i",
    province: "Hà Nội",
    rating: 5,
    date: "21/02/2023",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Anh Trần Trung",
    role: "Khách hàng mua xe Audi A4",
    province: "Nam Định",
    rating: 5,
    date: "04/09/2022",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Toyota Fortuner tại TimeCarsAuto.",
    name: "Anh Hồ Hoàng",
    role: "Khách hàng mua xe Toyota Fortuner",
    province: "Ninh Bình",
    rating: 4,
    date: "16/11/2023",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Chị Ngô Lan",
    role: "Khách hàng mua xe Hyundai Tucson",
    province: "Hải Phòng",
    rating: 5,
    date: "28/04/2024",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Anh Lê Phúc",
    role: "Khách hàng bán xe Kia Morning",
    province: "Thái Bình",
    rating: 5,
    date: "09/01/2023",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Anh Hồ Hùng",
    role: "Khách hàng mua xe VinFast Fadil",
    province: "Lào Cai",
    rating: 5,
    date: "15/08/2022",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe Kia Seltos nhận được. Rất khuyến khích!",
    name: "Chị Đỗ Oanh",
    role: "Khách hàng mua xe Kia Seltos",
    province: "Hà Nam",
    rating: 5,
    date: "26/03/2024",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Anh Bùi Quân",
    role: "Khách hàng bán xe",
    province: "Bắc Ninh",
    rating: 5,
    date: "07/12/2022",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Chị Vũ Anh",
    role: "Khách hàng mua xe Mazda CX-5",
    province: "Phú Thọ",
    rating: 5,
    date: "18/06/2023",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Chị Đặng Thảo",
    role: "Khách hàng mua xe Honda CR-V",
    province: "TP. Hồ Chí Minh",
    rating: 5,
    date: "30/09/2023",
  },
  {
    quote: "Chiếc Toyota Camry mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Phan Tài",
    role: "Khách hàng mua xe Toyota Camry",
    province: "Bình Dương",
    rating: 5,
    date: "12/04/2022",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Nguyễn Duy",
    role: "Khách hàng mua xe Ford Explorer",
    province: "Đồng Nai",
    rating: 5,
    date: "23/01/2023",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Chị Trần Giang",
    role: "Khách hàng mua xe BMW X5",
    province: "Đà Nẵng",
    rating: 4,
    date: "05/07/2024",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Anh Võ Toàn",
    role: "Khách hàng bán xe",
    province: "Khánh Hòa",
    rating: 5,
    date: "17/10/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Mercedes-Benz E-Class ưng ý cho gia đình mình.",
    name: "Anh Huỳnh Minh",
    role: "Khách hàng mua xe Mercedes-Benz E-Class",
    province: "Lâm Đồng",
    rating: 5,
    date: "28/05/2022",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Audi Q7 tại TimeCarsAuto.",
    name: "Chị Phạm Hồng",
    role: "Khách hàng mua xe Audi Q7",
    province: "Bà Rịa - Vũng Tàu",
    rating: 5,
    date: "11/03/2023",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Hoàng Hiếu",
    role: "Khách hàng mua xe Lexus RX350",
    province: "Bình Định",
    rating: 5,
    date: "22/08/2023",
  },
  {
    quote: "Thủ tục mua bán xe nhanh gọn, minh bạch. TimeCarsAuto đã hỗ trợ tôi rất nhiều từ khâu chọn xe đến lúc hoàn tất giấy tờ. Sẽ quay lại trong tương lai.",
    name: "Chị Lê Yến",
    role: "Khách hàng mua xe VinFast Lux A2.0",
    province: "Hà Tĩnh",
    rating: 5,
    date: "03/06/2024",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe Hyundai Santa Fe nhận được. Rất khuyến khích!",
    name: "Anh Trần Kiên",
    role: "Khách hàng mua xe Hyundai Santa Fe",
    province: "Gia Lai",
    rating: 4,
    date: "14/01/2022",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Chị Nguyễn Tú",
    role: "Khách hàng mua xe Kia Seltos",
    province: "Đắk Lắk",
    rating: 5,
    date: "25/09/2022",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Anh Phạm Bình",
    role: "Khách hàng mua xe Ford Ranger",
    province: "Kon Tum",
    rating: 5,
    date: "08/04/2023",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Anh Hoàng Hải",
    role: "Khách hàng mua xe Toyota Vios",
    province: "Quảng Nam",
    rating: 5,
    date: "19/11/2023",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Huỳnh My",
    role: "Khách hàng mua xe Honda City",
    province: "Quảng Ngãi",
    rating: 5,
    date: "01/07/2022",
  },
  {
    quote: "Chiếc Mitsubishi Xpander mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Phan Mạnh",
    role: "Khách hàng mua xe Mitsubishi Xpander",
    province: "Phú Yên",
    rating: 5,
    date: "13/02/2024",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Chị Vũ Dung",
    role: "Khách hàng bán xe",
    province: "Bình Thuận",
    rating: 5,
    date: "24/07/2023",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Anh Võ Việt",
    role: "Khách hàng mua xe Porsche Macan",
    province: "Ninh Thuận",
    rating: 4,
    date: "06/05/2022",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Đặng Dũng",
    role: "Khách hàng mua xe BMW 320i",
    province: "Long An",
    rating: 5,
    date: "18/12/2023",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Chị Bùi Hương",
    role: "Khách hàng mua xe Audi A4",
    province: "Tiền Giang",
    rating: 5,
    date: "29/03/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Toyota Fortuner ưng ý cho gia đình mình.",
    name: "Anh Đỗ Thành",
    role: "Khách hàng mua xe Toyota Fortuner",
    province: "Bến Tre",
    rating: 5,
    date: "10/11/2022",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Anh Hồ Trung",
    role: "Khách hàng mua xe Hyundai Tucson",
    province: "Trà Vinh",
    rating: 5,
    date: "21/06/2024",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Ngô Hiền",
    role: "Khách hàng mua xe Kia Morning",
    province: "Vĩnh Long",
    rating: 5,
    date: "03/02/2022",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe VinFast Fadil tại TimeCarsAuto.",
    name: "Anh Dương Đức",
    role: "Khách hàng mua xe VinFast Fadil",
    province: "Đồng Tháp",
    rating: 5,
    date: "14/09/2023",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Chị Lý Ngọc",
    role: "Khách hàng mua xe Mazda CX-5",
    province: "An Giang",
    rating: 5,
    date: "26/04/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Kia Seltos ưng ý cho gia đình mình.",
    name: "Chị Đặng Nhi",
    role: "Khách hàng mua xe Kia Seltos",
    province: "Bà Rịa - Vũng Tàu",
    rating: 5,
    date: "08/01/2024",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Toyota Fortuner tại TimeCarsAuto.",
    name: "Anh Trần Trung",
    role: "Khách hàng mua xe Toyota Fortuner",
    province: "Sóc Trăng",
    rating: 5,
    date: "20/07/2022",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Phạm Thành",
    role: "Khách hàng mua xe BMW 320i",
    province: "Hải Phòng",
    rating: 5,
    date: "01/05/2024",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Chị Lê Anh",
    role: "Khách hàng mua xe Ford Explorer",
    province: "Tây Ninh",
    rating: 4,
    date: "13/12/2023",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Anh Hoàng Phúc",
    role: "Khách hàng bán xe",
    province: "Kiên Giang",
    rating: 5,
    date: "25/06/2023",
  },
  {
    quote: "Chiếc Toyota Vios mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Chị Võ Trang",
    role: "Khách hàng mua xe Toyota Vios",
    province: "Hà Nội",
    rating: 5,
    date: "07/03/2022",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe Hyundai Tucson nhận được. Rất khuyến khích!",
    name: "Anh Đỗ Hùng",
    role: "Khách hàng mua xe Hyundai Tucson",
    province: "Sơn La",
    rating: 5,
    date: "19/09/2022",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Chị Phan Hoa",
    role: "Khách hàng mua xe VinFast Lux A2.0",
    province: "Bạc Liêu",
    rating: 5,
    date: "01/04/2024",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Anh Nguyễn Quang",
    role: "Khách hàng mua xe Mitsubishi Xpander",
    province: "Yên Bái",
    rating: 4,
    date: "12/11/2023",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Đinh Việt",
    role: "Khách hàng mua xe Honda CR-V",
    province: "Cà Mau",
    rating: 5,
    date: "24/05/2023",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Dương Hà",
    role: "Khách hàng mua xe Porsche Macan",
    province: "Thừa Thiên Huế",
    rating: 5,
    date: "06/02/2022",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Anh Lê Minh",
    role: "Khách hàng mua xe Audi Q7",
    province: "Điện Biên",
    rating: 5,
    date: "18/08/2022",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Chị Hồ Loan",
    role: "Khách hàng bán xe",
    province: "Thái Nguyên",
    rating: 5,
    date: "30/03/2023",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Anh Bùi Thắng",
    role: "Khách hàng mua xe Mercedes-Benz E-Class",
    province: "Quảng Trị",
    rating: 5,
    date: "11/10/2023",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Chị Vũ Thúy",
    role: "Khách hàng bán xe",
    province: "Hà Giang",
    rating: 5,
    date: "23/04/2024",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Anh Hoàng Long",
    role: "Khách hàng mua xe Honda City",
    province: "Bắc Giang",
    rating: 5,
    date: "05/01/2022",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe Kia Morning nhận được. Rất khuyến khích!",
    name: "Chị Nguyễn Dung",
    role: "Khách hàng mua xe Kia Morning",
    province: "Cao Bằng",
    rating: 4,
    date: "17/07/2022",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Lexus RX350 ưng ý cho gia đình mình.",
    name: "Anh Phan Anh",
    role: "Khách hàng mua xe Lexus RX350",
    province: "Lạng Sơn",
    rating: 5,
    date: "29/02/2024",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Nguyễn Dũng",
    role: "Khách hàng mua xe BMW X5",
    province: "Hòa Bình",
    rating: 5,
    date: "10/09/2023",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Audi A4 tại TimeCarsAuto.",
    name: "Chị Lý Chi",
    role: "Khách hàng mua xe Audi A4",
    province: "Lai Châu",
    rating: 5,
    date: "22/04/2023",
  },
  {
    quote: "Chiếc VinFast Fadil mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Đoàn Bảo",
    role: "Khách hàng mua xe VinFast Fadil",
    province: "Quảng Bình",
    rating: 5,
    date: "04/12/2022",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Ngô Vân",
    role: "Khách hàng mua xe Ford Ranger",
    province: "Bắc Kạn",
    rating: 5,
    date: "16/07/2023",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Anh Trần Duy",
    role: "Khách hàng mua xe Hyundai Santa Fe",
    province: "Bình Phước",
    rating: 5,
    date: "28/02/2022",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Mazda CX-5 tại TimeCarsAuto.",
    name: "Anh Đinh Mạnh",
    role: "Khách hàng mua xe Mazda CX-5",
    province: "TP. Hồ Chí Minh",
    rating: 5,
    date: "11/09/2022",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Chị Phạm Hằng",
    role: "Khách hàng bán xe",
    province: "Đồng Nai",
    rating: 5,
    date: "23/05/2024",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Lê Huy",
    role: "Khách hàng mua xe Toyota Camry",
    province: "Bình Dương",
    rating: 5,
    date: "05/12/2023",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Chị Hoàng Hà",
    role: "Khách hàng mua xe Mercedes-Benz E-Class",
    province: "Hà Nội",
    rating: 5,
    date: "17/06/2023",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe BMW X5 nhận được. Rất khuyến khích!",
    name: "Anh Võ Sơn",
    role: "Khách hàng mua xe BMW X5",
    province: "Đà Nẵng",
    rating: 4,
    date: "29/01/2022",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Ford Explorer ưng ý cho gia đình mình.",
    name: "Anh Bùi Khánh",
    role: "Khách hàng mua xe Ford Explorer",
    province: "Hải Phòng",
    rating: 5,
    date: "10/08/2022",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Chị Phan Linh",
    role: "Khách hàng mua xe Audi Q7",
    province: "Cần Thơ",
    rating: 5,
    date: "22/03/2023",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Anh Dương Hoàng",
    role: "Khách hàng bán xe",
    province: "An Giang",
    rating: 5,
    date: "04/10/2023",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Chị Trần Ngọc",
    role: "Khách hàng mua xe Honda CR-V",
    province: "Bà Rịa - Vũng Tàu",
    rating: 5,
    date: "16/05/2024",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Nguyễn Trung",
    role: "Khách hàng mua xe Lexus RX350",
    province: "Bắc Giang",
    rating: 5,
    date: "28/11/2022",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Chị Lý Mai",
    role: "Khách hàng mua xe VinFast Lux A2.0",
    province: "Bắc Kạn",
    rating: 5,
    date: "09/07/2023",
  },
  {
    quote: "Chiếc Hyundai Santa Fe mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Hoàng Bình",
    role: "Khách hàng mua xe Hyundai Santa Fe",
    province: "Bạc Liêu",
    rating: 4,
    date: "21/02/2022",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Anh Ngô Hiếu",
    role: "Khách hàng mua xe Kia Seltos",
    province: "Bắc Ninh",
    rating: 5,
    date: "03/09/2022",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Chị Hồ Huệ",
    role: "Khách hàng mua xe Ford Ranger",
    province: "Bến Tre",
    rating: 5,
    date: "15/04/2024",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Toyota Vios tại TimeCarsAuto.",
    name: "Anh Đỗ Quang",
    role: "Khách hàng mua xe Toyota Vios",
    province: "Bình Định",
    rating: 5,
    date: "27/11/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Honda City ưng ý cho gia đình mình.",
    name: "Chị Đặng Anh",
    role: "Khách hàng mua xe Honda City",
    province: "Bình Phước",
    rating: 5,
    date: "08/06/2023",
  },
  {
    quote: "Đội ngũ nhân viên chuyên nghiệp, am hiểu về xe. Tôi rất ấn tượng với quy trình kiểm định 176 hạng mục, tạo sự an tâm tuyệt đối.",
    name: "Anh Vũ Mạnh",
    role: "Khách hàng mua xe Mitsubishi Xpander",
    province: "Bình Thuận",
    rating: 5,
    date: "20/01/2022",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Chị Bùi Quyên",
    role: "Khách hàng mua xe Porsche Macan",
    province: "Cà Mau",
    rating: 5,
    date: "02/08/2022",
  },
  {
    quote: "Tôi đã bán lại chiếc xe cũ của mình tại đây và được định giá rất cao, thủ tục lại nhanh gọn. Chắc chắn sẽ giới thiệu cho bạn bè và người thân.",
    name: "Anh Trần Đức",
    role: "Khách hàng bán xe",
    province: "Cao Bằng",
    rating: 5,
    date: "14/03/2023",
  },
  {
    quote: "Chế độ bảo hành 1 năm của TimeCarsAuto làm mình rất yên tâm. Đây là điều khác biệt lớn so với những nơi khác.",
    name: "Anh Phan Hùng",
    role: "Khách hàng mua xe BMW 320i",
    province: "Đắk Lắk",
    rating: 5,
    date: "26/09/2023",
  },
  {
    quote: "Tìm được một nơi bán xe cũ uy tín như TimeCarsAuto thật khó. Mọi cam kết đều được thực hiện đúng. Cảm ơn showroom rất nhiều.",
    name: "Chị Võ My",
    role: "Khách hàng mua xe Audi A4",
    province: "Đắk Nông",
    rating: 4,
    date: "08/05/2024",
  },
  {
    quote: "Ấn tượng với cách làm việc của showroom. Mọi thông tin về xe đều công khai, rõ ràng. Mình đã giới thiệu mấy người bạn tới đây rồi.",
    name: "Anh Nguyễn Phong",
    role: "Khách hàng mua xe Toyota Fortuner",
    province: "Điện Biên",
    rating: 5,
    date: "20/12/2022",
  },
  {
    quote: "Bán xe ở TimeCarsAuto được giá tốt, thủ tục nhanh chóng, tiền về tài khoản ngay. Rất hài lòng.",
    name: "Chị Lê Hoa",
    role: "Khách hàng bán xe",
    province: "Đồng Tháp",
    rating: 5,
    date: "01/07/2023",
  },
  {
    quote: "Chiếc Hyundai Tucson mua ở đây đi thích lắm. Cảm ơn đội ngũ TimeCarsAuto đã tư vấn giúp mình chọn được chiếc xe phù hợp với nhu cầu và tài chính.",
    name: "Anh Hoàng Nam",
    role: "Khách hàng mua xe Hyundai Tucson",
    province: "Gia Lai",
    rating: 5,
    date: "13/02/2022",
  },
  {
    quote: "Mức giá TimeCarsAuto đưa ra rất cạnh tranh so với thị trường. Tôi cảm thấy mình đã có một món hời lớn với chất lượng xe Kia Morning nhận được. Rất khuyến khích!",
    name: "Chị Huỳnh Nhi",
    role: "Khách hàng mua xe Kia Morning",
    province: "Hà Giang",
    rating: 5,
    date: "25/08/2022",
  },
  {
    quote: "Từ khâu tư vấn online đến lúc xem xe trực tiếp đều rất chu đáo. Các bạn nhân viên nhiệt tình, dễ mến.",
    name: "Anh Phạm Việt",
    role: "Khách hàng mua xe VinFast Fadil",
    province: "Hà Nam",
    rating: 5,
    date: "07/04/2024",
  },
  {
    quote: "Chất lượng xe lướt ở đây đúng như cam kết. Xe gần như mới, mọi thứ đều được kiểm tra kỹ lưỡng. Rất an tâm khi mua xe Mazda CX-5 tại TimeCarsAuto.",
    name: "Anh Đặng Tuấn",
    role: "Khách hàng mua xe Mazda CX-5",
    province: "Hà Tĩnh",
    rating: 5,
    date: "19/11/2023",
  },
  {
    quote: "Dịch vụ ở TimeCarsAuto thực sự tuyệt vời. Các bạn tư vấn rất nhiệt tình, xe thì chất lượng không chê vào đâu được. Tôi đã tìm được chiếc xe Toyota Camry ưng ý cho gia đình mình.",
    name: "Chị Vũ Lan",
    role: "Khách hàng mua xe Toyota Camry",
    province: "Hải Dương",
    rating: 4,
    date: "01/06/2023",
  },
  {
    quote: "Mình ở tỉnh xa nhưng vẫn được hỗ trợ rất nhiệt tình. Xe được vận chuyển về tận nhà, chất lượng đúng như mô tả. 10 điểm cho dịch vụ!",
    name: "Anh Hồ Sơn",
    role: "Khách hàng mua xe Mercedes-Benz E-Class",
    province: "Hậu Giang",
    rating: 5,
    date: "13/01/2022",
  },
  {
    quote: "Đã tham khảo nhiều nơi nhưng cuối cùng chốt mua xe ở TimeCarsAuto vì sự chuyên nghiệp và minh bạch. Xe đi rất êm, gia đình mình rất thích.",
    name: "Chị Ngô Tâm",
    role: "Khách hàng mua xe BMW X5",
    province: "Hòa Bình",
    rating: 5,
    date: "25/07/2022",
  },
  {
    quote: "Lần đầu mua xe cũ nhưng mình rất hài lòng với TimeCarsAuto. Xe đẹp, giá tốt, nhân viên tư vấn có tâm. Sẽ ủng hộ dài dài.",
    name: "Anh Dương Bảo",
    role: "Khách hàng mua xe Ford Explorer",
    province: "Hưng Yên",
    rating: 5,
    date: "06/03/2024",
  }
]).flat());
